.github/workflows/lint.yml, lib/handlers/quote/quote.ts, lib/handlers/schema.ts, package-lock.json, package.json
update package-lock, goes to version2
=> Fix Build + catchup on linting

lib/cron/cache-config.ts
Disabled celo alfajores for v3-subgraph
=> disabled celo alfajores v3-subgraph because we don't have subgraph provider

lib/handlers/injector-sor.ts, lib/handlers/quote/injector.ts
Fixes issue where batch params for Celo in SOR get overridden by default batch params in routing-api
=> Fixed batch params override issue cause celo quotes to fail

bin/stacks/routing-api-stack.ts
alarm was configured improperly
=> fixed simulation alarm

bin/stacks/routing-api-stack.ts, test/integ/quote-to-ratio.test.ts, test/integ/quote.test.ts
Remove integration tests for the deprecated chains.
=> Rcmpbell remove rinkeby from 2 xx alarms 3

lib/handlers/quote/quote.ts, package-lock.json, package.json
Added 2 metrics in the routing api to keep track of the amounts and buckets that are currently being generated.
=> Add metrics to track amounts from a hardcoded list of pairs

bin/app.ts
This commit updates RPC urls to new ones
=> feat: update rpc urls

bin/app.ts
bump the ip rate limit to 3000 if stage is beta. doing this for load testing, will revert back after testing is finished.
=> temp bump rate limit for beta

bin/app.ts
Reverts Uniswap/routing-api#127
=> Revert "temp bump rate limit for beta"

bin/app.ts, lib/handlers/handler.ts
- feat: update polygon rpc url
- Fix code style issues with Prettier
- feat: update rpc urls
=> rpc url update

lib/dashboards/cached-routes-widgets-factory.ts, lib/handlers/router-entities/route-caching/marshalling/cached-routes-marshaller.ts, package-lock.json, package.json
Bumping SOR to 3.10.4 and updating Marshaller to include the originalAmount added in SOR 3.10.4
=> Bump SOR to 3.10.4

lib/handlers/router-entities/route-caching/cached-routes-configuration.ts
Adding new configurations of pairs to track and testing more generalized configurations
=> Caching configurations for tracking new pairs

lib/dashboards/cached-routes-widgets-factory.ts
- Add more fields to the cached routes dashboard
- fix error
=> Updated cached routes logs dashboard

lib/dashboards/cached-routes-widgets-factory.ts, package-lock.json, package.json
- Update Dashboard to include misquote rates
- Title of misquote graphs
=> Include metrics for misquotes in dashboard

lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
This reverts commit 8ef98daaf25e6346dc8b1878e8cb7b0955fa1164.
=> Revert "Turn off Livemode cache to collect metrics (#173)"

lib/handlers/injector-sor.ts
This reverts commit a71074e2e22fc3ff3599dd0e6f18d99935a9a0bf.
=> Revert "Service log level changed to Warn (#176)"

test/unit/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
=> fix: update failing unit test

lib/handlers/quote/quote.ts, lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- Update tracked pairs to consider the wrapped symbol
- fix for wrapped token
=> Fix logs for route metrics using wrapped tokens

package-lock.json, package.json
This reverts commit 60cc5d390d96be908f1727bae2a56486fd78a648.
=> Revert "Bump SOR to 3.11.4 (#200)"

package-lock.json, package.json
This reverts commit 5021afd6b3defc77e3aa3e18062565abd3572d0a.
=> Revert "Revert "Bump SOR to 3.11.4 (#200)" (#202)"

bin/stacks/routing-api-stack.ts
Removing for now due to too many non-actionable alerts. We also have alarms for 5xx and 4xx errors (% greater than a certain threshold) so removing this won't cause us to miss any of the errors we "actually care about".
=> chore: remove 2xx alarm for now

bin/stacks/routing-dashboard-stack.ts, lib/handlers/quote/quote.ts
- number of requests metric
- Split graphs for better visibility
- update dash
=> Tweak Dashboard with metrics per chain

lib/handlers/injector-sor.ts
See https://github.com/Uniswap/smart-order-router/pull/250 for details.
=> fix: revert multicall chunksize for optimism

package-lock.json, package.json
Current 3.13.1
3.13.2: https://github.com/Uniswap/smart-order-router/pull/265
New 3.13.2
=> bump sor to 3.13.2

package-lock.json, package.json
=> Update SOR to 3.13.2-hotfix

bin/stacks/routing-caching-stack.ts, lib/cron/cache-config.ts
- Revert "Update CachePool params (#252)"
- set page size to 500
=> Revert incorrect change

package-lock.json, package.json
copy pasta https://github.com/Uniswap/routing-api/pull/254
=> fix: hotfix

bin/stacks/routing-dashboard-stack.ts, lib/dashboards/rpc-providers-widgets-factory.ts
Reverting previous changes
Skipping the chain if the url is undefined
Translating chainId to chain name
=> Fix RPC metrics receiving unresolved variables

lib/cron/cache-config.ts, lib/dashboards/rpc-providers-widgets-factory.ts
Adding BASE chain to the job that exports the pool cache from subgraph to S3 and IPFS
=> Add BASE to PoolCacheLambda

package-lock.json, package.json
=> Bump SOR to 3.15.3

bin/app.ts
Increasing provisioned concurrency to RoutingAPI
=> Increase provisioned concurrency

bin/stacks/routing-api-stack.ts, bin/stacks/routing-database-stack.ts, bin/stacks/routing-lambda-stack.ts
Creating a Table that will keep track of the caching requests sent out, to avoid sending the same requests multiple times
=> Create Table for flagging caching requests

bin/stacks/routing-database-stack.ts, lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts, lib/handlers/router-entities/route-caching/model/protocols-bucket-block-number.ts
- Create SecondaryLocalIndex to query irrespective of buckets
- only perform search across buckets for optimistic quotes
=> Create a secondary index to query across bucket amounts

bin/app.ts, bin/stacks/routing-api-stack.ts, bin/stacks/routing-lambda-stack.ts, lib/handlers/quote/quote.ts, lib/handlers/quote/schema/quote-schema.ts
Tested on @jsy1218 local:
https://app.warp.dev/block/9V6k9d4rX6CWFpt18LA6SZ
=> Create a debugRoutingConfig param and a UnicornSecret

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/323 into routing-api
=> bump sort to 3.15.11

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/329
=> bump sor to 3.15.14 for mixed routes latencies improvements

package-lock.json, package.json
Updating SOR to 3.16.0 that contains the candidate selection refactor
=> Bump SOR 3.16.0

package-lock.json, package.json
Bumping SOR containing one more fix for the heuristics refactor
=> Bump SOR to 3.16.2

package-lock.json, package.json
release https://github.com/Uniswap/smart-order-router/pull/355
=> bump sor for sort & no in-memory copy candidate pools speedup

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/359
=> bump sor to 3.16.10 in routing-api

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/374
=> bump sor to 3.16.16

bin/stacks/routing-api-stack.ts, bin/stacks/routing-database-stack.ts, bin/stacks/routing-lambda-stack.ts
In preparation for the generalized CachedRoutes (aka RoutesDB) I'm creating these DDB tables
=> Create RouteDB Dynamo Tables

lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts, test/mocha/unit/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
Switch RoutesDB to Livemode from Tapcompare
=> Switch RoutesDB to livemode

bin/stacks/routing-lambda-stack.ts
=> Increase memory

bin/stacks/routing-database-stack.ts, bin/stacks/routing-lambda-stack.ts
=> add warning comments

bin/app.ts, bin/stacks/routing-dashboard-stack.ts
- Better estimate for provisioned concurrency
- 390
=> Provisioned concurrency part deux

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/406
=> bump sor to 3.16.26

lib/handlers/injector-sor.ts, package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/408
=> Bump sor to 3.16.27

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/410
=> bump sor to 3.16.28

package-lock.json, package.json
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Release https://github.com/Uniswap/smart-order-router/pull/412
=> bump sor to 3.16.29

package-lock.json, package.json, test/mocha/integ/quote.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/415 
Parallelize FOT quote requests in integ-test to repro the race condition in https://github.com/Uniswap/smart-order-router/pull/415 on good probability.
=> Chore: Bump sor to 3.16.30 and enhance FOT integ test to catch race condition on some possibility

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/417
=> bump sor to 3.16.31

package-lock.json, package.json, test/mocha/integ/quote.test.ts
release https://github.com/Uniswap/smart-order-router/pull/421
=> bump sor to 3.16.33

test/mocha/integ/quote.test.ts
Investigate swap simulation failure as follow-up https://linear.app/uniswap/issue/ROUTE-90/investigate-routing-api-fot-integ-test-exact-hardhat-fork-simulation
=> comment out fot hardhat swap simulation

lib/handlers/injector-sor.ts
=> feat: Update to use https for tenderly

lib/handlers/evm/provider/InstrumentedEVMProvider.ts
This reverts commit 5f89c24ee20fffaca8e70014593077eee8af55e1.
=> Revert "Cache eth_calls in our InstrumentedEVMProvider (#406)"

lib/handlers/evm/provider/InstrumentedEVMProvider.ts
This reverts commit 120909951efd8feb3220da0205fe7452cc6e7419.
=> Revert "Cache eth_calls with in-memory cache (#410)"

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/439
=> bump sor to 3.17.4

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/439
=> bump sor to 3.17.5

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/449
=> bump sor to 3.18.3

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/452
=> Chore: bump sor to 3.19.0

bin/stacks/routing-dashboard-stack.ts, lib/handlers/quote/quote.ts, lib/handlers/quote/schema/quote-schema.ts
=> Add resource source metrics to RoutingDashboard

bin/stacks/routing-api-stack.ts
Discussed during ops weekly, we will remove tenderly sev2, and make sev3 threshold much lower at 20%.
=> chore: remove tenderly sev2 and make sev3 20%

bin/stacks/routing-lambda-stack.ts
=> chore: New Polygon RPC

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/460
=> chore: bump sor to 3.19.3

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/483
=> fix: bump sor to 3.21.1

bin/app.ts
=> chore: Add one lambda to beta so tests dont time out

bin/stacks/routing-lambda-stack.ts
Increasing lambda version to refresh secrets
=> Increase lambda version

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/506
=> chore: bump sor to 3.24.5

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/508
=> chore: bump sor to 3.24.6

lib/handlers/injector-sor.ts
Forgot to add Sepolia in https://github.com/Uniswap/routing-api/pull/488
=> Add SEPOLIA to V2Supported

bin/stacks/routing-api-stack.ts, bin/stacks/rpc-gateway-dashboard.ts
Added dashboard so we can better monitor the launch.
=> Add RPC Gateway dashboard for RoutingAPI

bin/app.ts, bin/stacks/rpc-gateway-dashboard.ts, lib/config/rpcProviderProdConfig.json, test/mocha/unit/rpc/GlobalRpcProviders.test.ts
Similar to https://github.com/Uniswap/routing-api/pull/497.
Tested in local env.
=> Launch RPC Gateway for Celo, BNB, Polygon and Base

lib/handlers/injector-sor.ts, test/mocha/e2e/quote.test.ts
goerli needs to be disabled. validator stops producing new blocks https://goerli.etherscan.io/.
=> fix: disable goerli

bin/app.ts, bin/stacks/rpc-gateway-dashboard.ts, lib/config/rpcProviderProdConfig.json, test/mocha/unit/rpc/GlobalRpcProviders.test.ts
This reverts commit 9070233e738d9f882efc22d9f48b91e694cdfc49.
It failed to deploy because it now exceeds 4KB size limit for env variables...
=> Revert "Launch RPC Gateway for Celo, BNB, Polygon and Base (#499)"

package-lock.json, package.json
On release pipeline, the test consistently fails with:
> 1) quote
> 128 | "before all" hook in "quote":
> 129 | InternalError: Unknown transaction type 3
> 130 | at ForkBlockchain._processRemoteBlock (/codebuild/output/src2138685608/src/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:300:15)
> 131 | at ForkBlockchain._getBlockByNumber (/codebuild/output/src2138685608/src/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:242:17)
> 132 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 133 | at ForkBlockchain.getBlock (/codebuild/output/src2138685608/src/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:66:13)
> 134 | at ForkBlockchain.getLatestBlock …
=> fix: upgrade hardhat to support dencun 

package-lock.json, package.json
After upgrading hardhat, we are hitting another dev dependency error:
> 1) quote
> 168 | "before all" hook in "quote":
> 169 | Cannot find module '@nomicfoundation/edr-linux-x64-gnu'
> 170 | Require stack:
> 171 | - /codebuild/output/src1541993516/src/node_modules/@nomicfoundation/edr/index.js
> 172 | - /codebuild/output/src1541993516/src/node_modules/hardhat/internal/hardhat-network/provider/provider.js
> 173 | - /codebuild/output/src1541993516/src/node_modules/hardhat/internal/core/providers/construction.js
> 174 | - /codebuild/output/src1541993516/src/node_modules/hardhat/internal/core/runtime-environment.js
> 175 | - /codebuild/output/src1541993516/src/node_modules/hardhat/internal/lib/hardhat-lib.js
> 176 | - /codebuild/output/src1541993516/src/test/mocha/e2e/quote.test.ts
> 177 | - …
=> fix: add edr platform dev dependencies

package-lock.json, package.json
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Release https://github.com/Uniswap/smart-order-router/pull/513
=> chore: bump sor to 3.25.1

lib/handlers/quote/injector.ts, package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/517
=> chore: bump sor to v3.26.0

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/521
=> chore: bump sor to 3.26.1, update ur address for blast

lib/config/rpcProviderProdConfig.json
=> [RPC Gateway] Launch 1% to BNB chain

lib/config/rpcProviderProdConfig.json
=> [RPC Gateway] Launch 1% to Optimism

lib/config/rpcProviderProdConfig.json
Since we roll out to 10% of Avalanche yesterday, the latency and success rate looks normal. 
Now we will fully launch on Avalanche.
=> [RPC Gateway] Fully launch on Avalanche

bin/stacks/routing-lambda-stack.ts
We need to update some secrets's value. Bumping lambda version to make sure to pick up the new value.
=> Bump RoutingLambda version

lib/config/rpcProviderProdConfig.json
Tested locally and no issues found. No errors from both major and shadow providers.
Verified that the correctness of major provider's URL with current prob lambda's environmental variables.
=> [RPC Gateway] Launch to 1% of Polygon

bin/stacks/routing-api-stack.ts
https://linear.app/uniswap/issue/CX-596/user-mentioning-they-may-be-blocked#comment-79dd6f7e
=> Increase rate limit of every 5 mins to 200

bin/app.ts, bin/stacks/rpc-gateway-dashboard.ts, lib/config/rpcProviderProdConfig.json, lib/rpc/utils.ts, test/mocha/unit/rpc/GlobalRpcProviders.test.ts, test/mocha/unit/rpc/rpcProviderTestProdConfig.json
Locally tested with both providers. Worked with no problem.
=> [RPC Gateway] Launch to 1% of Blast

lib/config/rpcProviderProdConfig.json
This is a first step of launching traffic split on RPC gateway. We want to make sure it work as expected on the testnet first.
=> [RPC Gateway] Split traffic for Sepolia

lib/rpc/SingleJsonRpcProvider.ts
Tiny adjustment on metrics reporting on RPC gateway provider call successes and fails.
=> [RPC Gateway] Improve metrics logging

lib/handlers/injector-sor.ts, lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts, package-lock.json, package.json
Log the accurate quote latencies within SOR. I tested in routing-api locally, and can see the latencies are looking expected now:
=> fix: quote latencies logging bug

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/532
=> feat: support fot on L2

lib/util/onChainQuoteProviderConfigs.ts
I forgot to configure the Polygon deploy block and gas threshold after shadow quoting in Polygon.
=> fix: polygon deploy block and gas threshold

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/550
=> chore: bump sor to v3.28.7 (release both FOT fix from @mikeki and quoter config changes from @jsy1218)

lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts, test/mocha/integ/handlers/quote/provider-migration/traffic-switch-quote-provider.test.ts
- Revert "live switch mainnet quote for 100 percent (#643)"
- Revert "feat: live switch polygon quote for 100 percent (#640)"
=> Revert live switch of Mainnet and Polygon

bin/app.ts, bin/stacks/routing-api-stack.ts, bin/stacks/routing-caching-stack.ts, lib/cron/cache-config.ts, package-lock.json, package.json
Create a secret for the alchemy query key, and use it to hit the Avalanche subgraph.
Avalanche subgraph is currently broken, so this change is low-risk.
=> Use AlchemySubgraph on Avalanche

lib/cron/cache-config.ts
Avalanche Subgraph migration went really well, so now I'm migrating BNB
=> Use Alchemy Subgraph for BNB

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/562
=> chore: bump sor to v3.28.10

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/565
=> chore: bump sor to v3.28.11

bin/app.ts, bin/stacks/routing-lambda-stack.ts, lib/config/rpcProviderProdConfig.json, lib/rpc/utils.ts
QuickNode provisioned RETH node. We should give it a latency evaluation.
=> feat: introduce quicknode reth on mainnet for shadow latency evaluation

lib/cron/cache-config.ts
Collecting more metrics with the threshold at 1k
=> chore(cron): Reduce untracked threshold

README.md, bin/app.ts, bin/stacks/routing-lambda-stack.ts, lib/config/rpcProviderProdConfig.json, lib/handlers/injector-sor.ts, lib/rpc/utils.ts, package-lock.json, package.json, test/mocha/e2e/quote.test.ts, test/utils/tokens.ts
Release https://github.com/Uniswap/smart-order-router/pull/585
Tested Zora integ-tests locally: https://app.warp.dev/block/inxfrI0hFnJS5VahqWAtOH
We have to remove Infura from configs, because otherwise by adding `QUICKNODE_7777777`, I tested in my local to see 4kb env var limit breach again https://app.warp.dev/block/Tb77t3C1JyVu4uGUHWpX18.
=> feat: support zora

lib/cron/cache-config.ts
The dencetralized network subgraph version 0.1.0 is giving incomplete data, I can try with the version 0.0.7-bf
=> fix(caching): Try older version of subgraph

lib/config/rpcProviderProdConfig.json, lib/rpc/utils.ts
Shadow sampling mainnet traffic to quicknode test key
=> chore: shadow sampling mainnet traffic to quicknode test key

lib/util/onChainQuoteProviderConfigs.ts
QN per-transaction gas limit: 4000000000, or 4 billion.0
3_000_000 * 1000 = 3 billion
6_000_000 * 250 = 1.5 billion
=> fix: higher gas limit and batch size on zksync

package-lock.json, package.json
release https://github.com/Uniswap/smart-order-router/pull/615
=> chore: bump sor to 3.35.7

package-lock.json, package.json
release https://github.com/Uniswap/smart-order-router/pull/617
=> chore: bump sor to 3.35.8

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/619
=> chore: bump sor to 3.35.9

package-lock.json, package.json
release https://github.com/Uniswap/smart-order-router/pull/623
=> chore: bump sor to 3.35.10

bin/stacks/routing-api-stack.ts
fix synth build fail - lowercase name needed
=> chore(gql): add sev3 alert fix

bin/app.ts, lib/config/rpcProviderProdConfig.json
we want to re-evaluate quicknode reth in L1 now.
=> feat: shadow test quicknode reth in L1

package-lock.json, package.json
release https://github.com/Uniswap/smart-order-router/pull/631
=> chore: bump sor to 3.35.12

lib/cron/cache-config.ts
Copying Mainnet timeout settings
=> chore(cron): Update timeouts for base

package-lock.json, package.json
https://github.com/Uniswap/smart-order-router/pull/639
Remove unncessary mainnet check when trying ethEstimateGas
=> Bump SOR version

.github/workflows/trufflehog.yml
Adds trufflehog secret scanner
=> chore(infra): add trufflehog

.github/workflows/semgrep.yml
=> chore(infra): add semgrep

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/644
=> chore: bump sor to 3.36.2

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/651
=> chore: bump sor to 3.37.2

lib/handlers/injector-sor.ts
=> feat: migrate to tenderly node endpoint at 100% on mainnet 

bin/stacks/routing-dashboard-stack.ts
add tenderly latencies to routing dashboard
ROUTE-230
=> chore(monitor): add tenderly latencies to routing dashboard

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/669
=> chore: bump sor to 3.43.0 - feat: implement v4-quoter with computeV4Routes and stub getQuotes

lib/handlers/injector-sor.ts, lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts, package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/679
=> chore: bump sor to 3.44.0 - feat: SOR modify on-chain-quote-provider to support v4 quoter

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/681
=> chore: bump sor to 3.45.0 - feat: implement v4 gas model

bin/stacks/routing-dashboard-stack.ts
Adding RPC gw latencies to routing dashboard
ROUTE-231
=> fix(dashboard): add RPC gw latencies

lib/handlers/injector-sor.ts, lib/handlers/quote/injector.ts, lib/handlers/quote/quote.ts, lib/handlers/quote/schema/quote-schema.ts, lib/handlers/schema.ts, package-lock.json, package.json, test/mocha/e2e/quote.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/682
=> chore: bump sor to 3.46.0 - feat: implement best swap route with v4 routes

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/687
=> fix(sor): bump sor to 3.46.2 - fix: div by zero on syntheticGasCostInTermsOfQuoteToken

lib/handlers/quote/SwapOptionsFactory.ts, package-lock.json, package.json, test/jest/unit/handlers/shared.test.ts, test/mocha/e2e/quote.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/692
=> chore: bump sor to 3.48.0 - feat: SOR support universal router version param as part of alpha router config

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/711
=> chore: bump sor to 3.56.0 - feat: v4 quoter support native currency quote

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/714
=> chore: bump sor to 3.57.0 - feat: mixed quoter to support native curerncy quote

lib/cron/cache-config.ts, lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts, lib/handlers/router-entities/route-caching/model/pair-trade-type-chain-id.ts, package-lock.json, package.json, test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
…uter native currencyIn, currencyIn, quoteCurrency support (#844)"
This reverts commit e76e7803dfce6040c117bab8dc25856c35614b00.
=> Revert "chore: bump sor to 4.0.0 - feat(breaking): top-level alpha router native currencyIn, currencyIn, quoteCurrency support (#844)"

lib/cron/cache-config.ts
v0.0.16 has a bug of not sync'ing v4 native currency pool. v0.0.20 should fix it.
=> chore: update v4 sepolia subgraph url

lib/config/rpcProviderProdConfig.json
Reverts Uniswap/routing-api#871
=> Revert "feat(unirpc): switch traffic for all chains at 100% (Mainnet 30%)"

lib/config/rpcProviderProdConfig.json
Moving Polygon off unirpc to see how much this changes overall latency.
=> chore: move polygon off unirpc for latency check

lib/util/tenderlyNewEndpointRolloutPercent.ts
=> feat: migrate 50% of base traffic to new tenderly sim endpoint

lib/graphql/token-fee-utils.ts
Adding DIONE token to FOT gql skip list
Request by CX
=> chore(gql): add DIONE to FOT gql skip list

lib/handlers/shared.ts
Base quote latency is long recently. Increasing the distribution percent to see if it helps.
=> fix: decrease splits temporarily to help quote latency

lib/config/rpcProviderProdConfig.json
Fully onboarding base on unirpc
Monitoring the 75% looks ok
=> chore(unirpc): increase Base from 75% -> 100%

lib/config/rpcProviderProdConfig.json
Observing a very small number of port errors
Will revert this one to investigate.
=> Revert "chore(unirpc): increase Base from 75% -> 100%"

lib/handlers/quote/quote.ts, lib/handlers/quote/util/simulation.ts, package-lock.json, package.json, test/jest/unit/handlers/util/simulation.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/780
=> bump sor to 4.8.7 - feat: tenderly sim status SlippageTooLow

package-lock.json, package.json
Release https://github.com/Uniswap/smart-order-router/pull/767
=> chore: bump sor to 4.8.8 - chore: add gas estimation quality metric

lib/config/rpcProviderProdConfig.json
reduce unirpc traffic to see if routing-api base latency can go down
=> chore(unirpc): Base traffic 75% -> 50%

bin/app.ts
=> fix: dont load WEB3_RPC secrets for newly introduced chains

test/mocha/e2e/quote.test.ts
=> fix: disable e2e tests for monad testnet + unichain sepolia

lib/config/rpcProviderProdConfig.json
Attempting to increase traffic for Mainnet on unirpc.
Going from 25% to 50% and will monitor.
=> chore(unirpc): Mainnet traffic 25% -> 50%

test/mocha/e2e/quote.test.ts
skip flaky FOT test blocking pipeline
=> fix(test): skip flaky FOT test blocking pipeline

lib/config/rpcProviderProdConfig.json
Attempting to increase traffic for Mainnet on unirpc.
Going from 50% to 75% and will monitor.
=> chore(unirpc): Mainnet traffic 50% -> 75%

lib/cron/cache-config.ts
forgot to put subgraph configs
=> fix: add arb, base, polygon v4 subgraph config

lib/util/gasLimit.ts
reduce `MONAD_UPPER_SWAP_GAS_LIMIT`
=> fix: reduce MONAD_UPPER_SWAP_GAS_LIMIT

package-lock.json, package.json, test/mocha/e2e/quote.test.ts
fix: cached routes undefined
npm install
=> fix: cached routes undefined

test/mocha/e2e/quote.test.ts
decrease "v4 included" tests quote amounts due to lower liq / flakiness in order to have clean pipeline.
We'll debug that flakiness with sims
=> fix(test): more fix flaky e2e tests

lib/handlers/injector-sor.ts, lib/util/tenderlyNewEndpointRolloutPercent.ts, package-lock.json, package.json
Add unichain tenderly node endpoint
Release https://github.com/Uniswap/smart-order-router/pull/825
Pending personal aws e2e test
=> fix: bump sor 4.17.13 - fix(tenderly): add unichain node endpoint

test/mocha/e2e/quote.test.ts
=> chore: enable unichain e2e tests

test/mocha/e2e/quote.test.ts
update e2e tests to use URA 2.0 header.
Also keep a couple of tests to run both on 2.0/1.2
Tested by running e2e against personal box
=> fix(e2e): update e2e tests to use URA 2.0 header

test/mocha/e2e/quote.test.ts
tested on my local https://app.warp.dev/block/XaY4tXmigZVbi3dqENwRf1
=> fix: test assert token address

bin/stacks/routing-dashboard-stack.ts
Attempt to fix missing testnet widgets data
=> fix(dashboard): attempt to fix testnets widgets with errors

lib/handlers/injector-sor.ts, package-lock.json, package.json, test/mocha/e2e/quote.test.ts
routing beta pipeline unblocked via increasing memory 8gb -> 16gb
=> chore: bump sor to 4.18.2 - fix: support mixed quote on rest of L2s

lib/handlers/quote/quote.ts, lib/handlers/quote/util/simulation.ts, package-lock.json, package.json, test/jest/unit/handlers/util/simulation.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/832
=> chore: bump sor to 4.19.0 - feat: tenderly sim status TRANSFER_FROM_FAILED

lib/graphql/token-fee-utils.ts
add A1C to VFOT list + convert other tokens to lowercase
=> fix: add A1C to VFOT list

test/mocha/e2e/quote.test.ts
Skip 2 exactOut zora tests to unblock pipeline
=> fix(e2e): flaky zora exactOut tests skip

test/mocha/e2e/quote.test.ts
=> fix(e2e): adjust zora amount due to low liquidity

package-lock.json, package.json
release https://github.com/Uniswap/smart-order-router/pull/845
=> fix: mixed quoter types/values length mismatch

package-lock.json, package.json
release https://github.com/Uniswap/smart-order-router/pull/847
=> chore: bump sor to 4.20.8 - update rest of L2s mixed quoter v1 addresses

lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts, lib/util/computeProtocolsInvolvedIfMixed.ts, test/jest/unit/handlers/util/computeProtocolsInvolvedIfMixed.test.ts, test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
part 1 of fixing cached routes mixed route against protocols mismatch - add protocolsInvolved column
=> fix: cached routes mixed routes requested protocols mismatch

bin/stacks/routing-lambda-stack.ts, lib/util/defaultBlocksToLiveRoutesDB.ts
=> fix: update async lambda timeout and cached routes default blocks for usdt0-usdc staled v4 routes

lib/util/defaultBlocksToLiveRoutesDB.ts
change to 1min for USDT0 -> USDC cached routes update
=> fix:  cached routes default blocks 15min -> 1min

lib/handlers/injector-sor.ts, lib/handlers/shared.ts
=> fix: 10% -> 20% distribution percent for op, world, uni, soneium

lib/cron/cache-config.ts
Increase timeout for base v3 subgraph fetch do to increasing size
=> fix(cron): increase base v3 subgraph timeout on cronjob

bin/stacks/routing-lambda-stack.ts
Increase our lambdas (sync/async) memory
=> chore: increase routing lambdas memory

lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
Reverts Uniswap/routing-api#1095
=> Revert "fix: reduce cached routes fetch for base"

lib/cron/cache-config.ts
also increase v3/v3 subgraph pools ETH TVL to 0.1 ETH to filter out more pools.
=> fix: increase v3/v4 base subgraph ETH tracked threshold 0.025 -> 0.1 ETH

package-lock.json, package.json
Ship https://github.com/Uniswap/smart-order-router/pull/866
=> chore: bump SOR to 4.21.6 - chore: add pool metrics on v2 getPools more

package-lock.json, package.json
bump sor to 4.21.12 - fix: ROUTE-467 Avoid caching
=> chore: bump sor to 4.21.12 - fix: ROUTE-467 Avoid caching

package-lock.json, package.json
Reverts Uniswap/routing-api#1111
=> Revert "chore: bump sor to 4.21.12 - fix: ROUTE-467 Avoid caching"

lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts, package-lock.json, package.json
bumping up version for https://github.com/Uniswap/smart-order-router/pull/880
=> chore: ROUTE-467 bump up version and pass swapOptions

lib/util/hooksAddressesAllowlist.ts, lib/util/v4HooksPoolsFiltering.ts
Adding Renzo and Aegis to the v4 hooks' allow list
=> route-502: Allowlist New Hooks: Renzo and Aegis

hardhat.config.js
first 10 signers from hardhat are no longer undelegated, we need to increase to 50
=> fix: hardhat 50 accounts siyujiang/hardhat-50-accounts

lib/util/hooksAddressesAllowlist.ts, lib/util/v4HooksPoolsFiltering.ts
allowlist Bunni hook
Also fixing two small typos from https://github.com/Uniswap/routing-api/pull/1123/files
=> ROUTE-532 allowlist Bunni hook

lib/cron/cache-pools.ts
tested working on my local now https://app.warp.dev/block/YLh3CzXUk5gOhZtkEgv7NR
=> fix: manually include 0 tvl ETH/BUNNI hooked pool siyujiang/eth-bunni-hooked-pool

lib/cron/cache-pools.ts, lib/util/hooksAddressesAllowlist.ts, lib/util/v4HooksPoolsFiltering.ts
ROUTE-546 allowlist WETH on UNICHAIN
=> ROUTE-546 allowlist WETH on UNICHAIN

package-lock.json, package.json
bump up SOR version to 4.21.19
=> bump up SOR version

lib/cron/cache-config.ts, lib/cron/cache-pools.ts, lib/util/hooksAddressesAllowlist.ts, lib/util/v4HooksPoolsFiltering.ts
ROUTE-545 allowlist WETH on OPTIMISM
=> ROUTE-545 allowlist WETH on OPTIMISM

lib/cron/cache-config.ts, lib/cron/cache-pools.ts, package-lock.json, package.json
Reverts Uniswap/routing-api#1132
=> Revert "chore: bump sor to 4.22.0 - feat: support euler hooks factory subgraph"

lib/handlers/injector-sor.ts, lib/handlers/quote/injector.ts, lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts, package-lock.json, package.json, test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
Rolling out OPTIMISM
SOR change: 
1. https://github.com/Uniswap/smart-order-router/pull/896
2. https://github.com/Uniswap/smart-order-router/pull/894
=> ROUTE-467 Rollout out cache invalidation chain by chain

package-lock.json
fixing package-lock from merge conflict from https://github.com/Uniswap/routing-api/commit/6fc83c0919092bac1a2afd8c74152cdd9ac8e5e7
=> chore: fixing package-lock from merge conflict

package-lock.json, package.json
Ship https://github.com/Uniswap/smart-order-router/pull/900
=> chore: bump sor - fix: increase subgraph pageSize for Base v4 as well

bin/stacks/routing-api-stack.ts, package-lock.json, package.json
- Finetune low volume alerts (increase evaluation periods)
- ship https://github.com/Uniswap/smart-order-router/pull/901
=> chore: finetune low-volume alerts / bump sor - chore: Increased pageSize for Base (all protocols)

package-lock.json, package.json
ship https://github.com/Uniswap/smart-order-router/pull/902
=> fix: bump sor 4.22.8 - fix: Routepath v4 pool fix

package-lock.json, package.json
Ship https://github.com/Uniswap/smart-order-router/pull/903
=> fix: bump sor 4.22.9 - fix: Routepath mixed pool fix

lib/util/v4HooksPoolsFiltering.ts
This is called by an async CRON job where the debug log lines are hard to trigger.
=> NO-ROUTE: updating log level from debug to info

lib/cron/cache-config.ts, package-lock.json, package.json
Incrrease base v2 subgraph pagesize to 10k
Bump sor to ship https://github.com/Uniswap/smart-order-router/pull/904 (extra logging)
=> chore: increase base v2 subgraph pagesize + bump sor

lib/util/hooksAddressesAllowlist.ts
Resolves ROUTE-601. Adds Zora Creator and Post hooks to the routing allowlist.
=> adding Zora creator and post hooks to allowlist

lib/util/hooksAddressesAllowlist.ts
https://linear.app/uniswap/issue/ROUTE-603
=> feat(hooks): allowlist doppler v4 hook on base

package-lock.json, package.json
Ship https://github.com/Uniswap/smart-order-router/pull/913
=> chore: bump sor 4.22.15 - fix(subgraph): increase base v3 pagesize

bin/stacks/routing-caching-stack.ts, lib/cron/cache-config.ts
new base graph, we also need new graph id
=> fix: new base graph

lib/handlers/injector-sor.ts
feat: re-enable v3 against v4 cross liquidty on base
=> feat: re-enable v3 against v4 cross liquidty on base

lib/util/hooksAddressesAllowlist.ts
https://linear.app/uniswap/issue/ROUTE-625/allowlist-limitorderhook
=> chore(hooks): allowlist LimitOrderHook

lib/util/hooksAddressesAllowlist.ts
❯ curl 'https://56wjv9zdd9.execute-api.us-east-2.amazonaws.com/prod/quote?amount=1000000000000&deadline=1800&enableFeeOnTransferFeeFetching=true&enableUniversalRouter=true&portionBips=25&portionRecipient=0x000000fee13a103A10D593b9AE06b3e05F2E7E1c&protocols=v4&quoteSpeed=standard&recipient=0xc7C6b256ea29207B6E0b05FDaFAEc8B667615BD8&simulateFromAddress=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266&slippageTolerance=0.5&source=uniswap-web&tokenOutAddress=0xc02fE7317D4eb8753a02c35fe019786854A92001&tokenInChainId=130&tokenInAddress=ETH&tokenOutChainId=130&type=exactIn&enableDebug=true&hooksOptions=HOOKS_ONLY' \
-H 'x-universal-router-version: 2.0'
{"methodParameters":{"calldata":"...","value":"0xe8d4a51000","to":"0xef740bf23acae26f6492b10de645d6b98dc8eaf3"},"blockNumber":"26091286","amount":"10000 …
=> ROUTE-626 Allowlist Panoptic Oracle Hook for Unichain
