Uniswap/routing-api

- package-lock.json
- package.json
To update cloudflare pool list and return a new attribute from the v2 subgraph query
> Bump SOR version to 2.6.1

- bin/stacks/routing-api-stack.ts
Sev2s will page people with high urgency, then escalate if no response
Sev3s will just notify the oncall (via push notifications to phone/email)
Migrated all the existing alarms to be Sev3s, added new alarms for Sev2
> Add differents alarms by severity

- bin/stacks/routing-caching-stack.ts
- lib/cron/cache-pools-ipfs.ts
- lib/cron/clean-pools-ipfs.ts
Plan is to push it out with dryRun set to true, check logs, then remove the flag in a subsequent PR
One note, the Lambda may timeout (lambdas have max 15 min duration). I think this is fine, we can just let it timeout, and schedule the lambda to run a few times a week
> Add cron for cleaning old IPFS pool caches

- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-caching-stack.ts
- lib/handlers/quote/quote.ts
- test/integ/quote.test.ts
* Lowered threshold for 5XX and Latency alarms so they get triggered more
* Increased threshold for poolcachetolambda and poolcachetoipfs alarms so they get triggered less
* Added metrics and Sev3 alarms for each chain for 200 Error % and 400 Error % 
* Improved tenderly simulation metrics and alarms
* Gorli integ tests failing due to lack of liquidity, temporarily commented it out
https://uniswaplabs.atlassian.net/jira/software/projects/TRD/boards/23?selectedIssue=TRD-105
> Update alarm thresholds, add new metrics+alarms for each individual chain, comment out goerli integ-tests

- bin/stacks/routing-api-stack.ts
The Rinkeby testnet [has been deprecated](https://blog.ethereum.org/2022/06/21/testnet-deprecation) so we should no longer have cloudwatch alarms for the chain.
> Exclude rinkeby from monitored chains.

- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-caching-stack.ts
- bin/stacks/routing-dashboard-stack.ts
- lib/cron/cache-config.ts
- lib/cron/cache-pools.ts
https://uniswaplabs.atlassian.net/jira/software/projects/TRD/boards/23?selectedIssue=TRD-105
https://uniswapteam.slack.com/archives/C02D07EM805/p1665108679405439 alarms like this are flooded eng ops. This is happening because V2 subgraph query keeps timing out and causes the poolCacheLambda to time out, which makes it seem that the whole cron failed, even though it worked for all other chains. After the lambda times out, it is retried. The cloudwatch rule is also configured to run this lambda once every 15 minutes. Because of this predictable failure on V2 and the retry policy, this lambda ends up stacking and running 4x concurrently, and spamming eng-ops with alerts.
Separate the pool cache lambda into multiple lambdas, one for each ChainId - Protocol pairing. Remove the pool cache …
> Split PoolCacheToS3Lambda to multiple lambdas by chain and protocol

- bin/stacks/routing-api-stack.ts
Without this change, a single failure within the last two evaluation periods would bring the failure percentage to 100% and trigger the alarms.
> fix: modify simulation alarm config to treat missing data as not problematic

- bin/stacks/routing-caching-stack.ts
Changing the expression for the pool cache lambda alarms to check if it has succeeded at least once in the interval.
> Adjust the expression for caching alarm.

- bin/stacks/routing-api-stack.ts
This PR adjust's the `GET /quote` endpoint's 2xx alarm, specifically changing the evaluation period from 5 minutes to 30.
> chore: adjust 2xx alarm evaluation period

- test/integ/quote.test.ts
integ-test was failing, this fixes the issue locally and should fix in pipeline too. Test was failing because the address on chain no longer has enough USDC for simulation to work.
> Updated from address for simulation integ-test

- bin/stacks/routing-api-stack.ts
This PR tries to make those alarms less sensitive to `ROUT_NOT_FOUND` responses
> chore: change 2xx alarm periods to one hour

- bin/stacks/routing-api-stack.ts
`aws_cloudwatch.MathExpression` itself takes a `period` param which overwrites the definitions of that for individual metrics within.
> fix: 2xx and simulation alarms

- lib/handlers/quote/quote.ts
As predicted by @willpote, there are so many routes that the metrics are not being helpful.
It will be easier to query logs, so I'm removing the metrics to avoid the cost of them.
> Remove hashed route metric

- bin/stacks/routing-api-stack.ts
We've been paged a few times for simulation errors. 
The errors were due to simulations reverting due to slippage checks, which is always a possibility with FOT tokens, so no actual bug with our implementation, just expected failures.
Currently our traffic is so low that a few errors can trigger our alarms. Raising the alarm threshold for now to avoid unnecessary pages.
> Adjust simulations alarm

- bin/stacks/routing-api-stack.ts
We keep getting false negatives on this alarm, as simulations can fail for many valid reasons (user doesn't have enough token in, too little received, etc). Removing the SEV2 alarm. Leaving SEV3 so we can still be alerted and double check its not an unexpected issue.
> Remove sev2 simulation alarm

- lib/handlers/router-entities/aws-metrics-logger.ts
- lib/handlers/shared.ts
- package-lock.json
- package.json
In a previous deployment we fixed an issue with LUSD not being used as a pool for routing but it came with the cost of higher latencies overall.
This branch attempts to reduce the latencies while keeping the fix for LUSD working.
> Improve latencies by reducing the topNSecondHop pools per second hop

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
It appears like the order of the protocols is different in the setCachedRoute vs the getCachedRoutes function.
This change will allow us to test that theory in a quick and simple code change
> Normalize order of protocols in sortKey

- lib/handlers/router-entities/route-caching/cached-routes-configuration.ts
- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- lib/handlers/router-entities/route-caching/model/cached-routes-bucket.ts
The idea behind this change is that, for pairs that have fragmented and low liquidity, we could get the N last best routes, then run the algorithm for finding the best route using these routes as candidates
I'm also removing the `maxSplits` filter from the Wildcard pairs, I have the theory that with this new algorithm of fetching the routes of the last N block, then limiting by a number of MaxSplits is not necessary.
> Create a new option for fetching the last N cachedRoutes and reducing it into 1

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
This PR is forcing all Livemode caches to be Tapcompare. This will only be done for a few hours as a way to collect metrics on the latency improvements
> Turn off Livemode cache to collect metrics

- lib/dashboards/cached-routes-widgets-factory.ts
The dashboard will now display a "Minimum" metric for the latency on quotes
> Add Minimum stat to latency dashboard

- package-lock.json
- package.json
This version of SOR implements some changes with how we resolve tokens that were previously impossible to resolve (due to symbol returning bytes32 instead of string)
> Bump SOR to 3.11.5

- lib/handlers/pools/pool-caching/v3/dynamo-caching-pool-provider.ts
We decided to reduce the TTL to 1 minute to begin with. The average block settlement time is between 10-15 seconds. We can adjust down as appropriate once we launch the distributed pools cache.
> [ROUTE-9] Reduce the v3 pool TTL to 1 minute

- bin/app.ts
- bin/stacks/routing-api-stack.ts
This commit adds an internal API key that allows unthrottled access to
routing api for internal services like URA
> feat: add internal api key

- lib/handlers/pools/pool-caching/v3/cache-dynamo-pool.ts
Along with [PR](https://github.com/Uniswap/routing-api/pull/211), we also want to start checking the dynamo caching provider's cache hit/miss rate. If the dynamo caching accuracy is higher, but the hit rate is low, then it defeats the purpose of the dynamo caching. 
I think [v3-quoter.ts](https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/quoters/v3-quoter.ts) doesn't pass block number and [mixed-quoter.ts](https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/quoters/mixed-quoter.ts) does. We most likely won't see a high hit rate, once we start shadow sampling the traffic.
Start exporting cache hit/miss metrics.
Rely on existing tests. Since dynamo caching pool is not wired, we won't see metrics getting exported until we merge …
> [ROUTE-9] add dynamo pool cache hit/miss metrics

- lib/handlers/quote/quote.ts
In order to categorize the 4XX errors, I'm introducing a single log per request that describes the error.
Also removing the finally block as it appears to have introduced additional latency
> Add Logs to 4xx error

- lib/handlers/quote-to-ratio/schema/quote-to-ratio-schema.ts
Circle has issued a new USDC coin natively on Arbitrum which got renamed from USDC to USDC.e, this change triggered our validation in the quoteToRatio response endpoint (not used in production) for only allowing alphanumeric symbols.
This is an incorrect assumption, so I'm removing this validation in order to unblock the release queue
> Update Response Validation for QuoteToRatio

- bin/stacks/routing-dashboard-stack.ts
- lib/handlers/quote/quote.ts
This branch adds a widget for Success Rate that also considers the 400s
We still need to categorize the 400 errors better, so for now the SR will be better perceived this way
> Add SR widget including 4XX errors

- bin/stacks/routing-dashboard-stack.ts
In this change I'm splitting the mainnets and testnets in the RoutingDashboard to make it easy to read
Deployed and tested, works correctly :)
Mainnets
Testnets
> Split Mainnets and Testnets in RoutingDashboard

- bin/stacks/routing-api-stack.ts
I was investigating why v3 cached pool dynamo table has 0% hit rate. Some were due to the missing block number getting passed down, but there's small portion of traffic due to entry not in the table. This means the block number actually got passed down. Looking further into the [logs](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252FRoutingAPIStack-RoutingLamb-RoutingLambda2C4DF0900-xxMl8mSwRJxq/log-events/2023$252F06$252F09$252F$255B20$255Db3f05ebce5f64d56a65c5f92a9beb161$3FfilterPattern$3DCached+pool+failed+to+insert),  I finally realized that all the dynamo insertion failed: 
Then I wanted to double confirm by checking the routing lambda role IAM [policies](https://us-east-1.console.aws.amazon.com/iamv2/home?re …
> [fix] [ROUTE-9] fix the lambda not grant access to v3 cached pool dynamo table

- test/integ/quote.test.ts
We were getting ETH<->UNI swap test failures:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="VM Exception while processing transaction: reverted with an unrecognized custom error", method="estimateGas", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","gasPrice":{"type":"BigNumber","hex":"0x01d1a94a2000"},"to":"0xEf1c6E67703c7BD7107eed8303Fbe6EC2554BF6B","value":{"type":"BigNumber","hex":"0x0162dddd86586f7bad"},"data":"0x3593564c000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000648764ca00000000000000000000000000000000000000000000 …
```
> [fix] fix ETH<->ETH swap test setup

- test/integ/quote.test.ts
Previous PR https://github.com/Uniswap/routing-api/pull/230 fix was too broad, and caused integ-test to fail in codepipeline again:
Possibly due to the market condition change. If we deserialize the data from the payload, we will see TooMuchRequested error, indicative of slippage. 
Because I was running `npm run test` in my local instead of `npm run integ-test`.
- All integ tests passed on my local now:
N/A
> [fix] fix simulate and swap exact out v2 eth <-> uni rightfully

- package-lock.json
- package.json
Current 3.12.1
- 3.12.2: https://github.com/Uniswap/smart-order-router/pull/246
- 3.12.3: https://github.com/Uniswap/smart-order-router/pull/248
- 3.12.4: https://github.com/Uniswap/smart-order-router/pull/250
- 3.12.5: https://github.com/Uniswap/smart-order-router/pull/252
New 3.12.5
> bump sor to 3.12.5

- lib/handlers/pools/provider-migration/v3/traffic-switch-v3-pool-provider.ts
- test/unit/handlers/pools/provider-migration/traffic-switch-pool-provider.test.ts
From the dynamo caching optimization change https://github.com/Uniswap/smart-order-router/pull/253/files, we realized that the liquidity part of the pool was used in that path, not quote. We want to export liquidity accuracy metrics.
Because TVL heuristics path is on the critical gas build model codepath as part of every route request.
We start exporting quote mismatch & liquidity mismatch metrics. We keep the high level match/mismatch metrics so we don't need to change the [dashboard](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#dashboards/dashboard/Temp).
Modified unit test to ensure the additional metrics getting exported.
Deployed to cdk via personal AWS account to verify new metrics:
N/A
> [ROUTE-9] add v3 liquidity accuracy metrics

- bin/stacks/routing-lambda-stack.ts
This PR sets the logRetention policy of 2 weeks to the Quote Lambda.
With this change all logs will now be deleted after 2 weeks reducing our log storage and spend.
> Set logRetention in Quote lambda

- lib/handlers/pools/pool-caching/v3/cache-dynamo-pool.ts
The TTL was not passed down for the `DynamoCachingV3Pool` class, so it defaults to 2 min as in the base class.
We are fixing the TTL to 1 min, and since we have the dynamo caching hit/miss rate monitoring. If there's no drop in the hit rate, this change only brings positive effect.
By passing down the TTL within `DynamoCachingV3Pool` class.
Testing is a bit difficult, since TTL is set as a epoch time, and we can't assert the epoch time from test, since the 1 min from now might be slightly different in the test than in the application.
N/A
N/A
> [fix] [ROUTE-9] fix the TTL not passed down

- test/integ/quote.test.ts
Continuation of https://github.com/Uniswap/routing-api/pull/231. Probably due to the same liquidity change in the same pool, we need to up the slippage in the test setup for exact out in v2.
Possibly due to the market condition change. If we deserialize the data from the payload, we will see TooMuchRequested error, indicative of slippage. 
Up the slippage.
- All integ tests passed on my local now
N/A
> [fix] fix swap exact out v2 eth <-> uni

- package-lock.json
- package.json
Current 3.13.0
3.13.1: https://github.com/Uniswap/smart-order-router/pull/262
New 3.13.1
> bump sor to 3.13.1

- lib/handlers/router-entities/route-caching/cached-routes-configuration.ts
This configuration adds a bucket for the pricing quotes sent by the interface.
> Add bucket for pricing quotes

- bin/stacks/routing-caching-stack.ts
- lib/cron/cache-config.ts
The CachePool lambda is not able to complete the cache of V2 in time.
In this branch I'm doing the following changes:
1. Double the page size of the V2 subgraph query from 250 to 500
2. Double the timeout from 15 minutes to 30 minutes
The total number of v2 pools is 202k (https://dune.com/queries/2657172?category=decoded_project&namespace=uniswap_v2&contract=Factory&blockchains=ethereum), and the lambda stops when it gets to ~50k, so in theory these changes should get us to the finish line.
> Update CachePool params

- lib/cron/cache-config.ts
Currently the V2SubgraphProvidcer used for the CachePoolLambda is using page size of 500, but the lambda is still timing out.
Increasing to 1000, which will max out all the potential optimizations we can do on this system.
> Increase PAgeSize for the V2SubgraphProvider

- lib/handlers/evm/provider/ProviderName.ts
- test/mocha/dynamoDBLocalFixture.ts
QuickNode RPC metrics are shown as UNKNOWN (We use QuickNode RPC for chain id 56 and 42220). We want to fix it to show QuickNode metrics.
Because QuickNode RPC endpoint has QuikNode instead of QuickNode. We were matching against QuickNode.
Match against QuikNode.
N/A
> [fix] [ROUTE-30] Fix RPC Provider QuickNode Metrics

- bin/stacks/routing-dashboard-stack.ts
- lib/dashboards/rpc-providers-widgets-factory.ts
Routing-API CodePipeline failed due to JSON RPC Provider URL not populated for some chain. 
After troubleshooting, we think some net don't have the JSON RPC Provider URLs from the secrets. This was not caught in personal CDK Stack, because personal CDK Stack loads from the .env file, which adds all the chains.
We add log to ensure not all the chains are skipped. We are also not throwing error for the missing URLs to see how many URLs are missing during the codepipeline deploy.
Can deploy to personal CDK Stack successfully. Can see the missing chain ids in the cfn output. I intentially removed avax mainnet from my local .env. integ-test all succeeded except for avax, because of a separate change in tokenlist.
N/A
> [fix] [ROUTE-34] Skip widgets for chain id with no provider

- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-dashboard-stack.ts
- lib/dashboards/rpc-providers-widgets-factory.ts
Since the AWS Secrets values (JSON Provider URLs) require resolving at Cloudformation prepare time, we decided to just hard code the chain id to the provider name based on the internal institutional knowledge.
Hardcoded value will behave the same across local CDK environment vs. prod:
> [fix] [ROUTE-34] hardcode chain id to provider name

- lib/handlers/router-entities/route-caching/cached-routes-configuration.ts
As seen in the following screenshot, there are some bursts of requests for 1 to 2 ETH, which are not using cached routes.
In order to reduce on the cost of those requests we should enable caches.
> Enable 1 to 2 ETH Caches as we are getting 25% of traffic for 1 ETH quotes

- lib/handlers/pools/util/pool-provider-traffic-switch-configuration.ts
We decided to turn off the sampling in dynamo caching pool. We found the sampling path has some inefficient code, and we already filed [ROUTE-63](https://linear.app/uniswap/issue/ROUTE-63/re-enable-dynamo-pool-caching-sampling-with-better-implementation-that) as a follow-up.
> do not sample dynamo caching pool

- test/mocha/integ/quote.test.ts
Previous fix https://github.com/Uniswap/routing-api/pull/279 was incomplete. Token amount was off and resulted in no route found https://app.warp.dev/block/NA2mbp1S9mj7XqP41K2QmN.
Fixed to ensure the route gets found https://app.warp.dev/block/jfv615OfaR9pZJNJTJ9Z3i.
> fix: routing-api base native->erc20 test

- lib/handlers/shared.ts
We have collected sufficient datapoints in potential quote latency improvements, hence reverting for now.
> Revert "Initial quote perf tuning by increasing the distribution percent from 5% to 10% for the mainnet (#285)"

- lib/handlers/quote/quote.ts
- lib/handlers/quote/schema/quote-schema.ts
- lib/handlers/shared.ts
The intent param will be used to indicate wether the quote request has the intent of caching, quoting or swapping
The intent will be used to modify the configuration sent to SOR
> Create intent param for tracking intent of quote

- bin/app.ts
- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-lambda-stack.ts
- lib/handlers/quote/quote.ts
- lib/handlers/quote/schema/quote-schema.ts
We revert, because the codepipeline beta-us-east-2 retry does not retrigger `RoutingAPI.Prepare`, which does not build `CloudFormation` resource anymore.
We did find the reason Codepipeline failed was due to:
```
User: arn:aws:sts::145079444317:assumed-role/cdk-hnb659fds-cfn-exec-role-145079444317-us-east-2/AWSCloudFormation is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:us-east-2:644039819003:secret:debug-config-unicornsecrets-jvmCsq because no resource-based policy allows the secretsmanager:GetSecretValue action (Service: AWSSecretsManager; Status Code: 400; Error Code: AccessDeniedException; Request ID: 0b587919-9f34-46c7-a0da-0809f2dfc06c; Proxy: null)
```
But we added the policy to secrets afterwards (it seems like we always manually …
> Revert "Create a debugRoutingConfig param and a UnicornSecret (#290)" - see more details in descriptions

- bin/app.ts
- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-lambda-stack.ts
- lib/handlers/quote/quote.ts
- lib/handlers/quote/schema/quote-schema.ts
We don't believe there's any wrong with the change, so we will revert revert again.
We revert, because the codepipeline beta-us-east-2 retry does not retrigger RoutingAPI.Prepare, which does not build CloudFormation resource anymore.
Screenshot 2023-08-20 at 2 44 27 PM
We did find the reason Codepipeline failed was due to:
```
User: arn:aws:sts::145079444317:assumed-role/cdk-hnb659fds-cfn-exec-role-145079444317-us-east-2/AWSCloudFormation is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:us-east-2:644039819003:secret:debug-config-unicornsecrets-jvmCsq because no resource-based policy allows the secretsmanager:GetSecretValue action (Service: AWSSecretsManager; Status Code: 400; Error Code: AccessDeniedException; Request ID: …
```
> Revert "Revert "Create a debugRoutingConfig param and a UnicornSecret (#290)" - see more details in descriptions (#301)"

- lib/handlers/quote/quote.ts
- lib/util/alpha-config-measurement.ts
Instead of measuring how many swaps will be impacted by distribution change in [smart-order-router](https://github.com/Uniswap/smart-order-router) https://github.com/Uniswap/smart-order-router/pull/308, we should determine the impact in routing-api directly, as we plan to increase the distribution in routing-api.
> measure distribution change

- lib/handlers/router-entities/route-caching/model/protocols-bucket-block-number.ts
The bucket in the secondary key might be affecting the sorting algorithm in dynamo. This padding should normalize it
> Add padding on secondary key

- lib/handlers/quote/quote.ts
- package-lock.json
- package.json
We are releasing together:
- quote and intent specified endpoint-level latencies to see fast quote improvements, if any @jsy1218 
- sor topByETH* heuristics optimizations @mikeki 
- sor cached blocked token list in-memory mapping optimization @mikeki 
We shipped both debugRoutingConfig endpoint as well as quoteFast endpoint. Don't seem to see the fast enough quote that we were expecting. We want to have more holistic view of the quoteFast endpoint with different quoteSpeed and intent query string params.
We know that topByETH* heuristics is slowing down the breaking of the for-loop in the subgraph pools. We want to see if we can make the loop break sooner if the topBaseNTokenInTokenOut luckily includes the topByETH*
On local profiling, it seems like cached block token list provider is …
> quote intent specific endpoint latencies

- lib/handlers/handler.ts
- lib/handlers/injector-sor.ts
- lib/handlers/quote/injector.ts
- lib/handlers/quote/quote.ts
- lib/handlers/schema.ts
- package-lock.json
- package.json
We are instrumenting at the truly top-request level, because we suspect there's some levels of lambda cold start in the static initialization and “lazy” initialization.
Tested on personal AWS account, and see the metrics:
We are also releasing:
https://github.com/Uniswap/smart-order-router/pull/358
https://github.com/Uniswap/smart-order-router/pull/366
https://github.com/Uniswap/smart-order-router/pull/367
> instrument top level latencies and requests across cached routes hit vs non-cached routes hit

- lib/handlers/quote/quote.ts
Bug that hitsCachedRoutes from sor did not propogate to the quote response correctly.
> pass down hitsCachedRoutes

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
When the sample is a negative number the metrics go haywaire, so we should normalize to 0 if that's a route from a newer block
> Fix metric for blocks difference

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- package-lock.json
- package.json
As a way to increase our cache coverage, we are considering increasing our allowed cachedRoutes.
Previously if the cachedRoute was expired we would ignore it and cause a cache miss, now if the cached route is expired we will allow it.
There's a curent change in SOR that would instead change the cacheMode to `Tapcompare` when that route is expired, so this will not impact current behavior, but we will start collecting metrics about misquotes
We will use those metrics to make a go/no-go decision
> Allow expired cachedRoutes to be returned

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
Previously we would only sample for a given amount every time the flag was missing. This change will now force our RoutesDb to have atleast 1 samples for a given bucket in the same block
> Sample more frequently for caching requests

- bin/stacks/routing-lambda-stack.ts
Node version 14 and 16 have been deprecated, bump to version 18
> Bump Node version to 18 for the Lambda runtine

- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-database-stack.ts
- bin/stacks/routing-lambda-stack.ts
After cleaning up the code references to obsolete RouteCachingDB and CacheReqFlagDB  in https://github.com/Uniswap/routing-api/pull/342, we see there's zero prod traffic:
Next is to remove the table from the CDK stack.
> remove obsolete RouteCachingDB and CacheReqFlagDB

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- lib/handlers/shared.ts
We are going to implement Tapcompare for caching requests, but we need to make sure we avoid an infinte loop of lambdas calling themselves.
> Adding comments on important configuration

- bin/app.ts
I've been noticing some spottiness in the metrics after we reduced the provisioned concurrency, so I'm going back to the previous setting.
> ProvisionedConcurrency back to 500

- lib/handlers/quote/quote.ts
- lib/handlers/quote/schema/quote-schema.ts
Interface already fetches fee-on-transfer tax and shave off the quote amount. We need to protect smart-order-router  fee-on-transfer tax [feature](https://github.com/Uniswap/smart-order-router/pull/395/files) under a feature flag, so that interface doesn't double FOT tax.
> Expose enableFeeOnTransferFeeFetching query string param

- lib/handlers/router-entities/aws-subgraph-provider.ts
We only see request clock skew in routing lambda fetching subgraph pools from s3 in the normal quote path, [log insights](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*27The*20difference*20between*20the*20request*20time*20and*20the*20current*20time*20is*20too*20large*27*0a*7c*20sort*20*40timestamp*20desc~queryId~'3717b579fb703-fa61eb13-4b25139-cd23cee0-9749051fbd25664239e5e~source~(~'*2faws*2flambda*2fprod-us-east-2-RoutingAPI-Ro-RoutingLambdaF7AD8A1A-erFTueZgLnZ1~'*2faws*2flambda*2fprod-us-east-2-RoutingAPI-R-RoutingLambda2C4DF0900-Bbcx5MI4vlM6~'*2faws*2f …
> aws subgraph provider use correct clock skew

- lib/handlers/router-entities/aws-token-list-provider.ts
we can use maxRetries = 3/maxAttempts = 4, since this retry only happens during lambda instantiation time. Cold start is better than constantly failing lambda, that makes routing-api down. We've seen bad routing-api downtime due to s3 clock skew within routing lambda during instantiation time.
> correct clock skew limited to aws token list provider only

- lib/handlers/injector-sor.ts
- lib/handlers/pools/pool-caching/v2/v2-dynamo-cache.ts
- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/400
Also due to https://github.com/Uniswap/smart-order-router/pull/397, which releases https://github.com/Uniswap/smart-order-router/pull/394, we have a compiling error in `V2DynamoCache`. Note `batchGet` is not being called anywhere today in prod.
> sor 3.16.24

- lib/handlers/pools/pool-caching/v2/v2-dynamo-cache.ts
Aside from the [FeeOnTransferDetector](https://etherscan.io/address/0x19C97dc2a25845C7f9d1d519c8C2d4809c58b43f#code) on-chain contract call failures, we want to make sure sor doesn't hide any other bug that doesn't set the FOT tax. I had a chance to retrieve a WETH/BITBOY pool caching from prod RA dynamo table, that has not BITBOY FOT tax:
| cacheKey  | block | item | TTL |
| ------------- | ------------- |------------- | ------------- |
| pool-1-0xA802E152244c6eC47F9a0337F4E62E47B6d6A2d0  | 18217380  | eyJwcm90b2NvbCI6IlYyIiwiY3VycmVuY3lBbW91bnRBIjp7ImN1cnJlbmN5Ijp7ImNoYWluSWQiOjEsImFkZHJlc3MiOiIweDRBNTAwRUQ2YWRkNTk5NDU2OUU2NjQyNjU4ODE2ODcwNUZjQzk3NjciLCJkZWNpbWFscyI6MTgsInN5bWJvbCI6IkJJVEJPWSJ9LCJudW1lcmF0b3IiOiI0ODAyNDkyNDg5Njk3MTAyNjc3MjAzOTg1NTIiLCJkZW5vbWluYXRvciI6IjEifSwidG9rZW5BbW9 …
> Chore: add WETH/BITBOY pool caching logging for debugging

- lib/handlers/pools/pool-caching/v2/v2-dynamo-cache.ts
- lib/handlers/shared.ts
In prod, ever since we enabled always fetching FOT fees for caching pool entities (https://github.com/Uniswap/smart-order-router/pull/415), the Infura RPC calls went up dramatically:
Also, V2PoolsLoad latencies have increased due to the same change:
Those were expected, since we are ensuring FOT quote stability/correctness over the latencies. So now, FOT quote will need to leverage the RoutesDB to improve perf as well as reduce infura RPC calls.
> Chore: remove not use cached routes for fot flag & Revert "Chore: add WETH/BITBOY pool caching logging for debugging 

- test/mocha/integ/quote.test.ts
Follow-up for https://github.com/Uniswap/routing-api/pull/378. We can no longer assert useCachedRoutes === !enableFeeOnTransferFeeFetching, since the test runtime may or may not hit cached routes with randomness.
> Chore: remove the test assertion that useCachedRoutes is negate of enableFeeOnTransferFeeFetching

- test/mocha/integ/quote.test.ts
This reverts commit c1e1dfb4ff67388c9e2e3d91adecbee746206b5a.
We want to re-enable FOT integ-test, now that we know that this revert https://github.com/Uniswap/routing-api/pull/383 unblocked the release pipeline.
> Revert "Revert "Skips FOT test (#382)""

- package-lock.json
- package.json
- test/mocha/integ/quote.test.ts
Release:
- SOR https://github.com/Uniswap/smart-order-router/pull/433
- v2-sdk https://github.com/Uniswap/v2-sdk/pull/149
Enhanced existing routing-api integ-test coverage, after removing all the excluded test assertions:
- https://github.com/Uniswap/routing-api/pull/381/files#diff-e193a17cd7d38af77f287fe6bcf1c109b80c24bff4f9a4e317e4c95ea6a1c047R1081-R1088
- https://github.com/Uniswap/routing-api/pull/386/files
> Chore: bump sor to 3.17.2 in routing-api & improve routing-api FOT integ-test

- bin/stacks/routing-lambda-stack.ts
Previously, we increased routing lambda memory from 1530mb to 2048mb https://github.com/Uniswap/routing-api/pull/349/files, and overall memory utilization decreased from 55% to 45%. We think 50% might be a sweet spot for saved memories/AWS bills meanwhile maintaining the latencies. 50% is roughly 1792mb.
> Chore: decrease routing lambda memory to 1792mb

- test/mocha/integ/quote.test.ts
Routing-api integration test failed with:
```
1) quote
121 | "before all" hook in "quote":
122 |  
123 | AssertionError: expected '5000000077916' to equal '5000000000000'
124 | + expected - actual
125 |  
126 | -5000000077916
127 | +5000000000000
128 |  
129 | at Context.<anonymous> (test/mocha/integ/quote.test.ts:254:50)
130 | at runMicrotasks (<anonymous>)
131 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
132 | at runNextTicks (node:internal/process/task_queues:65:3)
133 | at listOnTimeout (node:internal/timers:528:9)
134 | at processTimers (node:internal/timers:502:7)
135 |  
136
```
It's possible to see more token amount getting funded than hardcoded amount, because a single whale address can turn out be a whale across more than one token. As long as in the …
> Fix: integ-test setup for funding from whale wallets

- bin/stacks/routing-lambda-stack.ts
https://github.com/Uniswap/routing-api/pull/398 only made memory utilization to 44%:
No impact on tail latencies:
We are decreasing back to 1530mb to see if memory utilization can reach 50%.
> Chore: decrease routing lambda memory to 1530mb

- bin/stacks/routing-lambda-stack.ts
Reverts Uniswap/routing-api#400 because we saw small performance decreases
https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'AWS*2fLambda~'ConcurrentExecutions~'FunctionName~'prod-us-east-2-RoutingAPI-R-RoutingLambda2C4DF0900-Bbcx5MI4vlM6))~view~'timeSeries~stacked~false~region~'us-east-2~start~'-PT168H~end~'P0D~stat~'Maximum~period~300)&query=~'*7bAWS*2fLambda*2cFunctionName*7d*20Concurrent
> Revert "Chore: decrease routing lambda memory to 1530mb"

- bin/stacks/routing-dashboard-stack.ts
The spillover invocations metrics is supposed to be tracked using SUM instead of MAX per https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics.html#monitoring-metrics-invocation
Updating the metric.
Also, this change will re-roll the infura api keys that were updated in the AWS secret manager
> Fix spillover invocation metric

- lib/handlers/evm/EVMClient.ts
- lib/handlers/evm/provider/InstrumentedEVMProvider.ts
- lib/handlers/injector-sor.ts
From this issue in ethers: https://github.com/ethers-io/ethers.js/issues/901
We can switch to using the StaticJsonRpcProvider which avoids an unnecessary chainId call to infura, saving about 30% of requests to infura
> Switch to StaticJsonRpcProvider

- bin/stacks/routing-lambda-stack.ts
This change is just updating the version of the lambda which should force it to pick up the new secrets
> Update RoutingAPI lambda version to pick up new secrets

- lib/handlers/evm/provider/InstrumentedEVMProvider.ts
Bsed of the [interface's](https://github.com/Uniswap/interface/blob/main/src/rpc/StaticJsonRpcProvider.ts#L31-L52) caching mechanism, we are also adding the caching capabilities to our rpv provider
> Cache eth_calls in our InstrumentedEVMProvider

- lib/handlers/shared.ts
In this branch we are enabling tapcompare for caching quotes to track accuracy of RoutesDB
> Enable tapcompare for caching quotes

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
This change will change the behavior of how often we sample buckets in RoutesDB.
We currently have a RoutesDB that stores routes seen for the past 24 hours for every specific pair. This database is not really growing much, since most routes will tend to stay liquid within the same liquidity pools that are currently being traded.
We care about updating the database whenever theres a major change in liquidity, but that doesn't happen often, so we are setting some threshold for how often we sample each *bucket* of a given pair. (A bucket is a range of from amount to amount * phi), we are changing from sampling on every block to sampling less often to reduce the amount of sync request we send to the routing api.
We will likely have to play with the numbers based on the chain velocity (how …
> Only send Caching requests every X blocks

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/440. We need to merge this PR, in order to deploy the token-in native ETH gas estimate fix to routing-api
> bump sor to 3.18.0

- lib/handlers/quote/injector.ts
- test/mocha/integ/quote.test.ts
quote integ test is simulating from an address that does not hold enough ETH balance for eth input test. Using beacon chain deposit contract address instead.
> fix: integ test

- bin/stacks/routing-api-stack.ts
As a follow-up action item from https://www.notion.so/uniswaplabs/New-tokens-swap-outages-on-Wallet-due-to-Tenderly-enforcing-HTTPS-aad4719087f0407d8a9b21f0137fd070?pvs=4#86b9072133b949a6b9e636dfcca1e76e, we will need to be able to detect and alert, when the tenderly requests are no longer returning success (http status 200).
It makes sense to alert against universal router simulation, but not swap router 02, due to swap router 02 being intended to get deprecated. Also universal router simulation is the main simulation traffic volume.
1. If tenderly no longer returns HTTP 200, then there will be insufficient datapoints, turning into alarm, tested in local AWS account: ![Screenshot 2023-11-16 at 3 34 30 PM](https://github.com/Uniswap/routing-api/assets/91580504/67cc4e1a-6742-4421-8565-d5a1a …
> Chore: add tenderly simulation http status alarm

- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-dashboard-stack.ts
Tested in local routing-api, now the expression evaluates to OK:
Also routing dashboard now contains tenderly http-level success rate widget:
> Fix: make tenderly http-level success rate alarm loosened & add tenderly http-level success rate widget

- lib/handlers/injector-sor.ts
We have HTTP-level Tenderly success rate monitoring and alarm in prod now:
We can start to reduce the tenderly timeout from 5s to 4s. Right now the simulation request volume is < 1k/5min:
Based on P90, P95, and P99, I expect only occassionally P99 might get impacted, so that's less than 10 simulation per 5min:
> Chore: reduce tenderly timeout from 5s to 4s

- test/utils/forkAndFund.ts
routing-api release pipeline failed. There was insufficient error logs for debugging, so I added the original error and saw https://app.warp.dev/block/EQoDcTskq97QtG8bLCPndv.
Note the `BULLET` whale address `https://etherscan.io/address/0x171d311eacd2206d21cb462d661c33f0eddadc03` doesn't have sufficient native ETH to cover the BULLET token transfer to alice address. The fix is to let hardhat funded alice account sends 0.1ETH to each token whale address, so that each whale address has sufficient native ETH for token transfer gas.
After fixing the insufficient gas, all integ-test can pass https://app.warp.dev/block/scbZG6vBuR515Cbn0bUTtW.
> Test-Fix: fix bullet whale address insufficient gas

- lib/handlers/injector-sor.ts
We have tenderly timeout metrics tracking, and we see in generally timeout happens less than 0.2% of total request:
We are going to further decrease the tenderly timeouts.
> Chore: reduce tenderly timeout 3s to 2.5s

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/456
> Chore: bump sor to 3.19.2

- lib/handlers/quote/schema/quote-schema.ts
Since not all the clients have added the `source` param in their request, we have to make it optional to unblock deployment.
> Make `source` param optional in quote API

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/462, optional gas token support for gasless relayer.
> chore: bump sor to 3.20.0

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/467
> chore: bump sor to 3.20.1

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/474, underlying change is to fix Arbitrum gas estimate
> chore: bump sor to 3.20.2

- bin/app.ts
- bin/stacks/routing-lambda-stack.ts
Given the fact that the memory utilization is hovering over 50% for our lambda, this means that signifcant time is spent on garbage collection. Therefore, increasing the memory to notice if the performance will improve. Moreover, this should also decrease the time needed to execute, which might end up being cheaper all together.
Secondly, reducing the concurrency limit from 1000 to 500. Running this script I found that only 64177 / 103698620 in the past week had a cold start, something that is WAY too small and we are spending too much money on it. 
```
filter @type="REPORT" and ispresent(@duration)
| stats count() as coldStarts, avg(@initDuration), min(@initDuration), max(@initDuration) # by bin(5m)
| order by coldStarts desc
```
TODO:
I want to tinker with scalable targets for provision …
> Feat: Change concurrency and memory for routing lambda

- bin/stacks/routing-lambda-stack.ts
We want to route Polygon RPC provider from QuickNode back to Infura.
> chore: bump lambda version to route Polygon RPC provider from QuickNode back to Infura

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/488 - v2 gas model on L2 for project deploy v2 everywhere
> chore: bump sor to 3.23.0

- test/mocha/e2e/quote.test.ts
BOND -> APE is failing in the pipeline. We already skip the same test in URA https://github.com/Uniswap/unified-routing-api/pull/351, this is despite some prior effort to attempt to make it more stable https://github.com/Uniswap/unified-routing-api/pull/349.
DAI -> WBTC test fails flakily, because the input DAI amount is too small. We replicate the same fix from https://github.com/Uniswap/unified-routing-api/pull/351.
Tested locally against prod endpoint: https://app.warp.dev/block/MHT4cW8PmLJWImHHtw5BsS
> fix: two flaky tests

- lib/handlers/quote/quote.ts
When selecting the protocols to route, we will check if the request source is for ios or android, and as long as the chainId is different than mainnet, then we avoid routing through those protocols.
Applying to both v2 and mixed routes (which also use v2)
> Prevent routing v2 on mobile

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/503. This PR should supposedly unblock quote on testnets.
> chore: bump sor to v3.24.4

- lib/handlers/injector-sor.ts
- test/mocha/e2e/quote.test.ts
Wallet uses tenderly simulation. Default multipler is [1.3](https://github.com/Uniswap/smart-order-router/blob/main/src/providers/tenderly-simulation-provider.ts#L96). Routing-api overrides Arbitrum to 2.5, and this was to account for a bug on Tenderly back then after Nitro upgrade. Tenderly have fixed their side of bugs, so routing-api can remove 2.5 multipler. 
Also enable retry on integ-tests level.
> fix: arbitrum use default multipler and integ-tests retry 3 times

- lib/config/rpcProviderProdConfig.json
- lib/rpc/GlobalRpcProviders.ts
- lib/rpc/ProdConfig.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
- test/mocha/unit/rpc/ProdConfig.test.ts
This is helpful to control graduate roll out of RPC Gateway. We can control the percentage of AWS lambdas that use RPC Gateway instead of default single provider.
> Use probability control the turn on/off RPC Gateway for providers

- lib/handlers/injector-sor.ts
Swap on Goerli stops working, if the token pairs only have v2 pool. We decided to re-enable V2 support on [Goerli](https://uniswapteam.slack.com/archives/C021SU4PMR7/p1709074854035469?thread_ts=1708523311.172709&cid=C021SU4PMR7), because v2 sepolia is pointing to old 0x7a25 v2 router. 
One issue with enabling Goerli on V2 used to the v2 gas model throwing uncaught [exception](https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts#L261), but that's [fixed](https://github.com/Uniswap/smart-order-router/pull/507/files#diff-2fe4a092f36b8091262f7035638dc00530816382f3a1cca86927a6fd712e9c04R2092) now, so that as long as the v2 pool exists, we can return a quote, even without good gas estimate.
> chore: Re-enable goerli on V2

- lib/handlers/injector-sor.ts
SDKs have the wrong deploy addresses for Sepolia for V2, resulting in fund loss on Sepolia, if the best swap route goes through V2.
We disable Sepolia v2 routing support for now.
> chore: remove sepolia from v2 routing

- bin/app.ts
- bin/stacks/rpc-gateway-dashboard.ts
- lib/config/rpcProviderProdConfig.json
- lib/handlers/injector-sor.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
100% launch on Optimism traffic.
- Infura: 100% traffic
- Quicknode: 0% traffic, shadowing to collect latency metrics
- NirvanaLabs: 0% traffic, shadowing to collect latency metrics
- Alchemy: 0% traffic, shadowing to collect latency metrics
Also add related Optimism dashboard.
Manually tested on local environment.
> Launch RPC gateway for Optimism with new providers

- package-lock.json
- package.json
revert https://github.com/Uniswap/routing-api/pull/503
revert https://github.com/Uniswap/routing-api/pull/502
upgrade hardhat to only [2.20.0](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.20.0), because [2.21.0](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.21.0) stops supporting node 16, which was probably why the pipeline started failing.
I tested on my local with 2.20.0, and tests can run: https://app.warp.dev/block/PLZsVEjUMAZVB66UloA5JR. My understanding is that OS-dependent dependency error from https://github.com/Uniswap/routing-api/pull/503 is due to the introduction of EDR from [2.21.0](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.21.0).
> fix: downgrade hardhat to 2.20.0

- bin/stacks/routing-lambda-stack.ts
We are still trying to unblock the routing service, since the previos chave was successful at deploying beta we are gonna try to rename it back to see if we got out of some weiord AWS state
> chore(fix-cdk): Renaming the lambda back to Lambda2

- bin/app.ts
- bin/stacks/routing-lambda-stack.ts
- bin/stacks/rpc-gateway-dashboard.ts
- lib/config/rpcProviderProdConfig.json
- lib/rpc/GlobalRpcProviders.ts
- lib/rpc/utils.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
This launches RPC gateway to Avalance, Optimsm, Celo, BNB, Polygon and Base.
Testing
- Deploy to local env works
- Sample requests (for these 6 chains) to local env works
- Local env dashboard looks fine
- Didn't encounter env variable 4KB limit issue when deploying to local env
> Launch RPC gateway to 6 chains

- bin/app.ts
1 in beta lambda is too low. Recently we observe that the beta integ-test always fail in first couple times.
I can see spillovers:
> chore: increase beta provisioned concurrency to 5

- bin/app.ts
beta integ-tests keep failing with 502 during before hook. I checked beta metrics, and still see some spillovers:
> chore: increase beta provisioned concurrency to 10

- lib/util/testNets.ts
In the code pipeline, it failed building due to:
> Error: Unknown chain id: 999999999
>     at ID_TO_NETWORK_NAME (/codebuild/output/src3089245944/src/node_modules/@uniswap/smart-order-router/src/util/chains.ts:281:13)
>     at /codebuild/output/src3089245944/src/bin/stacks/routing-dashboard-stack.ts:113:78
>     at Array.map (<anonymous>)
>     at /codebuild/output/src3089245944/src/bin/stacks/routing-dashboard-stack.ts:108:27
>     at arrayMap (/codebuild/output/src3089245944/src/node_modules/lodash/lodash.js:653:23)
>     at map (/codebuild/output/src3089245944/src/node_modules/lodash/lodash.js:9622:14)
>     at Function.flatMap (/codebuild/output/src3089245944/src/node_modules/lodash/lodash.js:9325:26)
>     at new RoutingDashboardStack …
> fix: remove zora sepolia from testnets

- bin/app.ts
- lib/config/rpcProviderProdConfig.json
- lib/rpc/GlobalRpcProviders.ts
- lib/rpc/utils.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
- test/mocha/unit/rpc/UniJsonRpcProvider.test.ts
This is a reworked version of https://github.com/Uniswap/routing-api/pull/523, with a bug fix to picking up enough secret key for prod.
The fix is https://github.com/Uniswap/routing-api/pull/536/commits/378e67e34882912c60b90576d832429e8cc5e06d.
Turns out if we roll out with a probability, we need to load both legacy and new RPC gateway secrets into environment variables.
> Launch RPC Gateway to 1% of Celo traffic (with bug fix)

- bin/stacks/routing-api-stack.ts
We have too many noisy pages over the last couple days, flooding with the important alerts. To begin mitigate, we can stop alerting on testnets and unknown source together.
> chore: do not alert testnet and unknown source on sev-3

- bin/stacks/rpc-gateway-dashboard.ts
- lib/rpc/ProviderStateSyncer.ts
- lib/rpc/SingleJsonRpcProvider.ts
- lib/rpc/UniJsonRpcProvider.ts
- test/mocha/integ/rpc/ProviderStateSyncer.test.ts
- test/mocha/unit/rpc/SingleJsonRpcProvider.test.ts
- test/mocha/unit/rpc/UniJsonRpcProvider.test.ts
The logic DB sync rate limit has been improved to make the ownership much clearer between `SingleJsonRpcProvider` and `ProviderStateSyncer`. Previously the rate limit logic spanned across these two classes but now it's all in `SingleJsonRpcProvider`. Vague words like `maybe` are also removed to make the code easier to follow.
Added more unit test for checking the effect of DB sync rate limit.
More Cloudwatch metrics and dashboard graphs have also been added to verify the effect of local env testing and it will be very useful for production deployment monitoring.
Tested and verified in local env.
> [RPC Gateway] Optimize DB sync rate limit logic, add more metrics & dashboard graph

- lib/config/rpcProviderProdConfig.json
10% of Celo's traffic have been on RPC gateway for a day and the latency and success rate looks normal.
Fully launch won't increase the pressure to the major provider for Celo (Quicknode), but will increase the traffic for shadow provider (Infura). However we've seen very little shadow call made to Infura in the last few days after launch.
The QPS is about 0.1. So it won't add much pressure to Infura even if we turn it to full.
> [RPC gateway] Fully launch on Celo

- lib/config/rpcProviderProdConfig.json
Since we launch 1% to Avalanche yesterday (4/1) , we don't see major metrics diff.
Now we want to slightly add some traffic to Avalanche. From 1% to 10%.
> [RPC gateway] Launch on 10% of Avalanche

- bin/stacks/rpc-gateway-dashboard.ts
- lib/config/rpcProviderProdConfig.json
- lib/handlers/quote/quote.ts
We add more RPC gateway specific metrics that measures from the input side (GET QUOTE). Previously the metrics focused too much on the downstream side (call vendors).
Related dashboard is also updated.
This should be even more helpful to monitor our RPC gateway launches.
> [RPC Gateway] Add RPC Gateway specific Quote request count, fail count and latency metric

- lib/config/rpcProviderProdConfig.json
[**RPC Gateway Deployment Overall Progress Track**](https://docs.google.com/spreadsheets/d/1_pbkfn_dXDLgChfdtkWZqxl2SLfKyYDLbXe-8z3YQmo/edit#gid=0)
Yesterday we deployed to 1% of Optimism. Since then
The success rate is unstable, but it's irrelevant to the RPC gateway (deployment time is show in the graph)
If we zoom out and look at latency change, there's no visible one in overall.
If we only look at RPC gateway specific request,
There's very few 5xx quote error. But if you look at the error from providers using RPC gateway path:
There are always random errors here and there in the last 24 hours. So I would consider this more of a downstream issue.
RPC gateway's quote p99 latency is about 2k to 4k ms
This aligns with overall quote p99 latency
> [RPC Gateway] Launch to 10% of Optimism

- lib/config/rpcProviderProdConfig.json
[RPC Gateway Per Chain Status]([url](https://docs.google.com/spreadsheets/d/1_pbkfn_dXDLgChfdtkWZqxl2SLfKyYDLbXe-8z3YQmo/edit#gid=0))
Deployed to 1% BNB yesterday. Overall latency looks the same. Deploy time is 15:30
Look at RPC gateway specific latency. About 700ish ms, on par with total latency. Initial higher latency is supposed to be cold start of lambda after deployment.
No 5xx error from RPC gateway code path for Bnb
Overall BNB has the least risk because there's only one provider. No shadow call logic will be triggered.
> [RPC Gateway] Launch to 10% of BNB

- lib/config/rpcProviderProdConfig.json
We deployed to 10% Optimism on yesterday 16:35 UTC-7 time with https://github.com/Uniswap/routing-api/pull/552. After the deployment we do see a bit of latency increase
It looks like both RPC gateway path and other code path has latency increases, because we even see the median latency has increased
Considering RPC gateway only counts for 10% of the traffic, if only RPC gateway code path have higher latency, the median latency shouldn’t change. That’s why I think it’s caused by something else.
Then I found that the latency for send() api from Infura, which is our Optimism’s major provider, did increase around the end of 18 o’clock. 
This should explain the QUOTE latency increase that happened about 2 hours after deployment.
However, just to be safe, we will try 20% launch and see if the …
> [RPC Gateway] Launch to 20% Optimism

- lib/config/rpcProviderProdConfig.json
[RPC Gateway Per Chain Status]([url](https://docs.google.com/spreadsheets/d/1_pbkfn_dXDLgChfdtkWZqxl2SLfKyYDLbXe-8z3YQmo/edit#gid=0))
We deployed BNB from 1% to 10%. https://github.com/Uniswap/routing-api/pull/553. Prod updated happened at 8:47
Overall latency is stable
Success rate 100%
No 5XX error
> [RPC Gateway] Launch to 100% of BNB

- lib/config/rpcProviderProdConfig.json
[RPC Gateway Per Chain Status]([url]
(https://docs.google.com/spreadsheets/d/1_pbkfn_dXDLgChfdtkWZqxl2SLfKyYDLbXe-8z3YQmo/edit#gid=0))
Previously we increased traffic from 10% to 20% on Optimism. https://github.com/Uniswap/routing-api/pull/554 The deployment happened at 12:17.
Latency looks stable after deployment
Success rate didn't change after deployment.
Code path that went through the RPC gateway shows no 5xx error after deployment.
> [RPC Gateway] Full launch on Optimism

- bin/stacks/routing-lambda-stack.ts
We need to do a re-roll of production secret. This PR is to make sure the lambda pick the new secret value.
> Bump RoutingLambdaStack version

- lib/rpc/ProviderStateSyncer.ts
- lib/rpc/SingleJsonRpcProvider.ts
- test/mocha/unit/rpc/SingleJsonRpcProvider.test.ts
We've seen cases where, for major provider, DB sync happens but `SingleJsonRpcProvider` doesn't have a latency record that belongs to the method name white list. Since we are only syncing latency for whitelisted methods with DB, this ends up being a wasted opportunity to sync. The result could be losing expected latency numbers in the DB for major providers.
We fix this issue by adding one more check on entering sync: The method name needs to be included in the whitelist.
Local test verified cases like mentioned above no longer happens.
Other small logging tweaks are added.
> [RPC Gateway] Add method name check before DB sync for non-shadow call

- bin/stacks/routing-lambda-stack.ts
- lib/rpc/SingleJsonRpcProvider.ts
Previously, for major providers, we only record latency metrics if this latency is going to be synced to DB. This will cause misses of latency metrics in AWS for certain APIs of major providers. For example, in production, we found that the major provider only published metrics for `send` call, no other calls.
This PR fixes this problem.
In local dev, you can see that we have more latencies for major providers recorded (the major provider here is Infura).
Before (For Infura we only recorded latency for `send`)
After (For Infura we recorded latency for other APIs as well)
> [RPC Gateway] Always record all latency metric for major provider

- lib/config/rpcProviderProdConfig.json
Based on discussion with the team, we plan to roll up RPC gateway without using DB sync. This is the first PR to make sure no issue in production without DB sync on a testnet chain. If this works well, we will apply the same to other launched chains.
> [RPC Gateway] Turn off DB sync for Sepolia

- lib/config/rpcProviderProdConfig.json
After we deployed https://github.com/Uniswap/routing-api/pull/566 (Turn off DB sync for Sepolia), we verified that DB sync for Sepolia indeed dropped to zero:
While other chains, such as Avalanche, it's DB sync isn't affected
Latency reporting for different providers isn't affected:
So it worked as expected. As a follow up, we will disable DB sync for other launched chains in this PR.
> [RPC Gateway] Turn off DB sync on already launched chains

- bin/app.ts
- bin/stacks/routing-lambda-stack.ts
- bin/stacks/rpc-gateway-dashboard.ts
- lib/config/rpcProviderProdConfig.json
- lib/rpc/utils.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
- test/mocha/unit/rpc/rpcProviderTestProdConfig.json
Tested locally:
1. Set chain config to 
```
{
"chainId": 42161,
"useMultiProviderProb": 1,
"providerInitialWeights": [1, 0, 0, 0],
"providerUrls": ["INFURA_42161", "QUICKNODE_42161", "NIRVANA_42161", "ALCHEMY_42161"]
}
```
Then make a bunch of requests. We can see that the major provider is used while others are being shadow called.
2. Set chain config to 
```
{
"chainId": 42161,
"useMultiProviderProb": 1,
"providerInitialWeights": [1, 1, 1, 1],
"providerUrls": ["INFURA_42161", "QUICKNODE_42161", "NIRVANA_42161", "ALCHEMY_42161"]
}
````
We can see that four providers all served as major providers
and they shadow called each other
Also there are no errors from any of the providers from what I tested.
> [RPC Gateway] Launch 1% to Arbitrum

- lib/config/rpcProviderProdConfig.json
We deployed to 1% on Polygon: https://github.com/Uniswap/routing-api/pull/568. Deployment time is at 13:38
Polygon mainnet p99.9 latency stays regular
Success rate and 5xx error not affected by deployment (the spike is way after the deployment)
P99 latency using RPC gateway on Polygon
Is similar to the p99 latency overall on Polygon
> [RPC Gateway] Launch to 10% of Polygon

- lib/config/rpcProviderProdConfig.json
We launch to 1% of Arbitrum https://github.com/Uniswap/routing-api/pull/570  
Deployment finished around 16:00
Latency looks fine
No errors after deployment
No 5xx error for requests using RPC gateway
> [RPC Gateway] Deploy to 10% Arbitrum

- README.md
Tiny PR fixing a misspelt word that I found while working on forking this repo
> docs: misspelt word in README.md

- bin/app.ts
- bin/stacks/routing-lambda-stack.ts
- bin/stacks/rpc-gateway-dashboard.ts
- lib/config/rpcProviderProdConfig.json
- lib/rpc/utils.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
- test/mocha/unit/rpc/rpcProviderTestProdConfig.json
Locally tested with config 
```json
{
"chainId": 1,
"useMultiProviderProb": 1,
"providerInitialWeights": [1, 1, 1, 1],
"providerUrls": ["INFURA_1", "QUICKNODE_1", "NIRVANA_1", "ALCHEMY_1"]
}
```
and made sure quote request, regardless of the provider selection, has no error returned.
> [RPC Gateway] Launch to 1% Ethereum

- lib/config/rpcProviderProdConfig.json
We deployed to 1% of Base https://github.com/Uniswap/routing-api/pull/574. Deployment finished at 10:47
Latency stays the same
Success rates and error rate not affected
We don’t see 5xx errors using RPC gateway code path.
> [RPC Gateway] Launch to 10% Base

- lib/config/rpcProviderProdConfig.json
We deployed to 1% on Ethereum https://github.com/Uniswap/routing-api/pull/575. Deployment time is 11:32
Latency after deployment
Success rate and error rate
Is the drop related to RPC gateway?
There’s a spike on total 5xx quote errors
But RPC gateway code path didn’t contribute much to it (2 out of 79)
So we are confident to roll it out further to 10%
> [RPC Gateway] Launch to 10% Ethereum

- lib/config/rpcProviderProdConfig.json
Previously we deployed 1% to Blast https://github.com/Uniswap/routing-api/pull/578. Deployment finished around 14:30.
P99.9 latency looks the same as before
Success rate has not changed
No 5xx errors on RPC gateway code path
> [RPC Gateway] Launch to 10% of Blast

- lib/handlers/injector-sor.ts
- lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts
- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- lib/util/onChainQuoteProviderConfigs.ts
- package-lock.json
- package.json
- test/mocha/integ/handlers/pools/provider-migration/traffic-switch-pool-provider.test.ts
- test/mocha/integ/handlers/quote/provider-migration/traffic-switch-quote-provider.test.ts
- test/test-utils/mocked-dependencies.ts
We want to switch to new view-only quoter. But we are not ready to live migrate yet. In this PR, we want to achieve:
1. Shadow request very small percent of Polygon quote against the new quoter v2, without impacting the routing-api endpoint success rate at all.
2. Make small refactoring in this PR, as well as based on https://github.com/Uniswap/smart-order-router/pull/510, so that it's easy to make incremental changes, when we roll out quoter to
- same chain at incremental live traffic migration to new quoter v2
- to new chain with the shadow quote, meanwhile using the correct quote config params without the manual copy-paste errors
3. Collect sampling metrics against the shadow new quoter v2, so as to understand
- is new quoter faster than the existing quoter
- is new quoter way …
> feat: shadow quote new quoter v2 on Polygon Mumbai and Sepolia

- lib/handlers/injector-sor.ts
- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- package-lock.json
- package.json
New view-only [quoter](https://etherscan.io/address/0x5e55c9e631fae526cd4b0526c4818d6e0a9ef0e3#code) was just deployed on mainnet. We are ready to shadow sample the new view-only quoter after the bug fix.
Sampling rate is 0.1%, since total quoter call to the RPC providers are between 20-30k/minute:
Related, from the screenshot, I noticed that the shadow quoter metrics prefix was evaluated to undefined, i.e. 'undefinedQuoteTotalCallsToProvider'. I will fix by populating metric prefix to empty string for the current quote provider.
> feat: shadow sampling view-only quoter on mainnet

- package-lock.json
- package.json
Upgrade `aws-cdk-lib` to latest version as we need the use [LambdaAction](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch_actions.LambdaAction.html) for allowing lambda to be directly invoked by Cloudwatch Alarms.
> Upgrade aws-cdk-lib to 2.137

- lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts
In quote comparison, I noticed that we can log the quotes from current quoter and view-only quoter to be mismatch, even if both return null:
This is because in quote [provider](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts#L291), we only use null coalesce on the right side but not left side. Fix is to have null coalesce on the left side as well.
> fix: both null quote comparison

- lib/handlers/injector-sor.ts
From https://github.com/Uniswap/routing-api/pull/586, when I fixed the metrix prefix for the current quoter, I forgot to explicitly provide the current quoter v2 contract address https://github.com/Uniswap/routing-api/pull/586/files#diff-42941f26ebe3855c458055f7f2269f22a2f85265c24cb1c5ac8dd78d20e0a947R295. It resulted in the current quoter contract call failed, because it was trying to call contract address `ChainId_${chainId}_Quoter`, which is non-existent.
Local tests can pass again https://app.warp.dev/block/tvDpWU7EL4pwPiOC38uxUf
> fix: missing quoter v2 contract address

- lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts
- lib/util/onChainQuoteProviderConfigs.ts
I was investigating the case, where the current quoter will return the quote, meanwhile the new [view-only quoter](https://github.com/Uniswap/view-quoter-v3) does not:
After the investigation, I found it was due to the historical quote inquiry, i.e.g the quote request includes the block number before the [mainnet quoter](https://etherscan.io/address/0x5e55c9e631fae526cd4b0526c4818d6e0a9ef0e3#code) was deployed.
The fix is to ensure, if we are comparing the quote that's before the new quoter deploy block number, we skip the entire quote comparisons.
> fix: new quoter comparison not deployed bug

- lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts
- lib/util/onChainQuoteProviderConfigs.ts
- package-lock.json
- package.json
- test/mocha/integ/handlers/quote/provider-migration/traffic-switch-quote-provider.test.ts
- test/test-utils/mocked-dependencies.ts
Once SOR returns per-quote-call gasUsed and gasLimit (https://github.com/Uniswap/smart-order-router/pull/534), then routing-api can calculate per-quote call failure is due to likely out-of-gas error. 
I was deciding between using gasUsed and gasLimit vs the encoded error from the return data, but the [simulation](https://www.tdly.co/shared/simulation/39de04bb-d794-43b0-aed2-8ea31957ca77) shows me that the encoded error from the return data might not be accurate. For this simulation, the error indicates [SLP](https://docs.uniswap.org/contracts/v3/reference/error-codes), which is not true:
```
cast 4byte-decode 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000353504c000000000000000000000000000000000000000 …
```
> fix: current quoter out-of-gas quote comparison

- lib/handlers/injector-sor.ts
- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- package-lock.json
- package.json
New view-only [quoter](https://polygonscan.com/address/0x5e55c9e631fae526cd4b0526c4818d6e0a9ef0e3#code) was just deployed on polygon. We are ready to shadow sample the new view-only quoter after the bug fix.
Sampling rate is 0.5%, because the total RPC call volume between mainnet and polygon is about 5:1:
> feat: shadow sampling view-only quoter on polygon

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
Polygon mumbai stopped on April 13th https://polygon.technology/blog/polygon-pos-is-cooking-the-napoli-upgrade-means-better-ux-the-mumbai-testnet-takes-a-bow. We should no longer sample in Polygon Mumbai.
We might need to remove mumbai from the `SUPPORTED_CHAINS` all together.
> fix: stop sampling on polygon mumbai

- lib/handlers/injector-sor.ts
- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- lib/util/onChainQuoteProviderConfigs.ts
- package-lock.json
- package.json
Sample quote on Mainnet and Polygon shows that the accuracy is at 100%:
This is positive, and gives us confidence to sample quote more. We can either increase the existing chain traffic or deploy to new chain with small shadow sampling rate. Shadow sampling on new chain makes more sense, because if the new view-only quoter were to have bug, at this point, it's easier to discover the bug on a new chain, rather than keep sampling on the current chains.
New view-only [quoter](https://basescan.org/address/0xf0c802dcb0cf1c4f7b953756b49d940eed190221#code) was just deployed on base. We will sample base at half of the mainnet rate, because eth_call call is doubled at base than mainnet:
> feat: shadow sampling view-only quoter on base

- lib/handlers/quote/quote.ts
- test/jest/unit/handlers/quote.test.ts
ForceCrossProtocol flag would keep an empty array of protocols, and it would query alpha router using that empty array. SOR will then determine the protocol that it must request.
I accidentally tarted throwing 400s on this case since I wrongly assumed that an empty array of protocols was a failure case
> fix: when protocols is undefined throw error, otherwise query empty array

- lib/util/onChainQuoteProviderConfigs.ts
After shadow sampling in Arbitrum, I don't see a single match or mismatch quote on Arbitrum:
But we have sampling traffic to Arbitrum:
This tells me the within the [compareQuotes](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/quote/provider-migration/v3/traffic-switch-on-chain-quote-provider.ts#L224), it probably stopped because of the deploy block cutoff. I tried with my local routing-api, and I saw that the multicall returned the block number seemingly from L1, not from Arbitrum L2:
Then I checked Arbitrum [doc](https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/block-numbers-and-time) to see:
> // some Arbitrum contract:
> block.number // => returns L1 block number ("ish")
This is the case for us, because we get the block number from …
> fix: arbitrum deploy block for view-only quoter

- lib/handlers/injector-sor.ts
- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- lib/util/onChainQuoteProviderConfigs.ts
BSC RPC call is about 1/10th of mainnet, so we sample at 1% on BSC:
New view-only [quoter](https://bscscan.com/address/0x5e55c9e631fae526cd4b0526c4818d6e0a9ef0e3#code) was just deployed on BSC.
I already verified on local routing-api, and can see quote matches:
> feat: shadow sampling view-only quoter on bsc

- lib/handlers/injector-sor.ts
I forgot to make the change in injector-sor to enable the shadow sampling in blast https://github.com/Uniswap/routing-api/pull/611. As a result, that PR was a no-op to blast traffic. This PR is a quick fix to enable blast shadow sampling quote at 1%.
> fix: blast quote provider traffic switch

- lib/handlers/injector-sor.ts
- package-lock.json
- package.json
We want to be able to different the quoter protocol version by explicitly adding the `Mixed` vs `V3` metrics wording. This is done primary through SOR https://github.com/Uniswap/smart-order-router/pull/547
> fix: improve quote provider logging

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We are ready to live switch to new view-only quoter. We will do it in the following order:
First batch:
- CELO: 1% -> 100%
- AVAX: 1% -> 100%
- BNB: 1% -> 100%
Second batch:
- Blast: 1% -> 10% -> 100%
- OP: 1% -> 10% -> 100%
- Polygon: 1% -> 10% -> 100%
Third batch:
- Arb: 1% -> 10% -> 100%
- Base: 1% -> 10% -> 100%
- Mainnet: 1% -> 10% -> 100%
We check the following metrics before we decide to live switch on CELO:
- Is the success rate on the CELO endpoint and on each CELO RPC call consistent?
CELO endpoint shows the consistently high success rate:
- Is the latency on the CELO endpoint consistent?
CELO latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on CELO?
[CELO RPC call …
> feat: live switch celo quote for 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on AVAX:
- Is the success rate on the AVAX endpoint and on each AVAX RPC call consistent?
AVAX endpoint shows the consistently high success rate:
- Is the latency on the AVAX endpoint consistent?
AVAX latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on AVAX?
[AVAX RPC call volume](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_42220_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_42220_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42220_INFURA_call_SUCCESS~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42220_QUIKNODE_call_FAILED~'.~'.~(v …
> feat: live switch avax quote for 1 percent

- lib/handlers/router-entities/aws-subgraph-provider.ts
We are seeing increased lambda cold start, as well as provisioned concurrency spillovers. We suspect it's due to the S3 slow download due to the large pool file size:
We are explicitly logging the per s3 bucket key downloading latency. We expect to see either very high latency, or it doesn't get logged due to lambda-level timeout.
> chore: add s3 latency metrics

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on BNB:
- Is the success rate on the BNB endpoint and on each BNB RPC call consistent?
BNB endpoint shows the consistently high success rate:
- Is the latency on the BNB endpoint consistent?
BNB latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on BNB?
[BNB RPC call volume](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_42220_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_42220_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42220_INFURA_call_SUCCESS~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42220_QUIKNODE_call_FAILED~'.~'.~(visible~f …
> feat: live switch bnb quote for 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on CELO:
- Is CELO still sampling at 10%, meanwhile live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'CELO*20sampling*20percent~id~'e1))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'CELO*20traffic*20switch*20percent~id~'e2))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_42220~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_42220~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_42220~'.~'.~(id~'m3 …
> feat: live switch celo quote for 100 percent

- lib/handlers/injector-sor.ts
- lib/handlers/quote/injector.ts
During container injector, we instantiate a new global logger with [injector-sor](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/injector-sor.ts#L132-L137), without request id, or any identifier that can identifier which request it's part of:
```
const log: Logger = bunyan.createLogger({
name: this.injectorName,
serializers: bunyan.stdSerializers,
level: bunyan.INFO,
})
setGlobalLogger(log)
```
The reason for this is because, [buildContainerInjected()](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/injector-sor.ts#L131C16-L131C38) is called as part of  [QuoteHandlerInjector('quoteInjector').build()](https://github.com/Uniswap/routing-api/blob/main/lib/handlers/index.ts#L13), but we only start to get the request id from the lambda event within [new …
> fix: activity id to chain id quote injector and lambda handler event

- lib/handlers/router-entities/aws-subgraph-provider.ts
I want to make sure that the pool parsing in memory is not taking long, so logging that. And for each s3 object download and parsing, I also log the latency as part of the logging info, so that when we debug by activity id, we can see each s3 object download latency.
> chore: log pool parsing latency metrics

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on AVAX:
- Is AVAX still sampling at 10%, meanwhile live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'AVAX*20sampling*20percent~id~'e1~period~900))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'AVAX*20traffic*20switch*20percent~id~'e2~period~900))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_43114~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_43114~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ …
> feat: live switch avax quote for 100 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on BNB:
- Is BNB still sampling at 1%, meanwhile live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'BNB*20sampling*20percent~id~'e1~period~900))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'BNB*20traffic*20switch*20percent~id~'e2~period~900))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_56~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_56~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_56~'.~'. …
> feat: live switch bnb quote for 100 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on Blast:
- Is the success rate on the Blast endpoint consistent?
Blast endpoint shows the consistently high success rate:
- Is the latency on the Blast endpoint consistent?
Blast latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on BNB?
[Blast RPC call volume](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_81457_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_81457_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_81457_INFURA_call_SUCCESS~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_81457_QUIKNODE_call_FAILED~'.~'.~(visible~false))~(~'.~' …
> feat: live switch blast quote for 1 percent

- lib/config/rpcProviderProdConfig.json
After the deployment of https://github.com/Uniswap/routing-api/pull/583 and https://github.com/Uniswap/routing-api/pull/629, we are ready to test auto fallback and recover in production.
The first chain we want to test is Sepolia because it's a testnet with small but meaningful amount of traffic. Even if we bring it down, the cost is still acceptable.
According to the prod alarm data, if we enable it for Sepolia, this is the only alarm that will possibly trigger: The latency alarm for Alchemy-Sepolia pair (Showing data from the last 24h, [link]([url](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(id~'expr_1~expression~'p50Latency))~(~'Uniswap~'RPC_GATEWAY_11155111_ALCHEMY_evaluated_latency_getBlockNumber~'Service~'RoutingAPI~(stat~' …
> [RPC Gateway] Enable auto fallback and recovery on Sepolia

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on Optimism:
- Is the success rate on the Optimism endpoint consistent?
Optimism endpoint shows the consistently high success rate:
- Is the latency on the Optimism endpoint consistent?
Optimism latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on Optimism?
[Optimism RPC call volume](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_10_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_10_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_10_INFURA_call_SUCCESS~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_10_QUIKNODE_call_FAILED~'.~'.~(visible~fal …
> feat: live switch optimism quote for 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on Polygon:
- Is the success rate on the Polygon endpoint consistent?
Polygon endpoint shows the consistently high success rate:
I checked the errors, and those were due to division by zero error, so it's related to the tokenIn/tokenOut.
- Is the latency on the Polygon endpoint consistent?
Polygon latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on Polygon?
[Polygon RPC call volume](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_137_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_137_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_13 …
> feat: live switch polygon quote for 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on Arbitrum:
- Is the success rate on the Arbitrum endpoint consistent?
Arbitrum endpoint shows the consistently high success rate:
- Is the latency on the Arbitrum endpoint consistent?
Arbitrum latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on Arbitrum?
[Arbitrum RPC call volume](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_42161_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_42161_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42161_INFURA_call_SUCCESS~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42161_QUIKNODE_call_FAILED~'.~'.~ …
> feat: live switch arbitrum quote for 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on Base:
- Is the success rate on the Base endpoint consistent?
Base endpoint shows the consistently high success rate:
- Is the latency on the Base endpoint consistent?
Base latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on Base?
[Base RPC call volume](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_42161_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_*208453_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_8453_INFURA_call_SUCCESS~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_8453_QUIKNODE_call_FAILED~'.~'.~(visible~false))~(~'.~'RPC_G …
> feat: live switch base quote for 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to live switch on Mainnet:
- Is the success rate on the Mainnet endpoint consistent?
Mainnet endpoint shows the consistently high success rate:
- Is the latency on the Mainnet endpoint consistent?
Mainnet latency does not change after the quote shadow sampling:
- Is the RPC call volume only slightly up after quote shadow sampling on Mainnet?
[Mainnet RPC call volume]([https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'ChainId_1_V3QuoterQuoteLatency~'Service~'RoutingAPI~(visible~false))~(~'.~'ChainId_1_ShadowV3QuoterQuoteLatency~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_1_INFURA_call_SUCCESS~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_1_QUIKNODE_call_FAILED~'.~'.~(visible~false))~(~'.~ …
> feat: live switch mainnet quote for 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on Blast:
- Is Blast live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'BLAST*20sampling*20percent~id~'e1~period~900))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'BLAST*20traffic*20switch*20percent~id~'e2~period~900))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_81457~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_81457~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_81457~'.~'.~(id~'m3~visibl …
> feat: live switch blast quote for 100 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on Arbitrum:
- Is Arbitrum live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'Arbitrum*20sampling*20percent~id~'e1~period~60))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'Arbitrum*20traffic*20switch*20percent~id~'e2~period~60))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_42161~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_42161~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_42161~'.~'.~(id~ …
> feat: live switch arbitrum quote for 100 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on Optimism:
- Is Optimism live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'Optimism*20sampling*20percent~id~'e1~period~900))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'Optimism*20traffic*20switch*20percent~id~'e2~period~900))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_10~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_10~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_10~'.~'.~(id~'m3~vis …
> feat: live switch optimism quote for 100 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on Polygon:
- Is Polygon live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'Polygon*20sampling*20percent~id~'e1~period~900))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'Polygon*20traffic*20switch*20percent~id~'e2~period~900))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_137~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_137~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_137~'.~'.~(id~'m3~visi …
> feat: live switch polygon quote for 100 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We check the following metrics before we decide to increase traffic switch on Base:
- Is Base live traffic switched at 1%?
Based on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'Base*20sampling*20percent~id~'e1~period~900))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'Base*20traffic*20switch*20percent~id~'e2~period~900))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_8453~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_8453~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_8453~'.~'.~(id~'m3~visible~false …
> feat: live switch base quote for 100 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- test/mocha/integ/handlers/quote/provider-migration/traffic-switch-quote-provider.test.ts
We check the following metrics before we decide to increase traffic switch on Mainnet:
- Is Mainnet live traffic switched at 1%?
Mainnet on the [metrics](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~(expression~'*28m1*2bm2*29*2f*28m1*2bm2*2bm3*2bm4*29*2a100~label~'Mainnet*20sampling*20percent~id~'e1~period~900))~(~(expression~'*28m5*2bm6*29*2f*28m5*2bm6*2bm7*2bm8*29*2a100~label~'Mainnet*20traffic*20switch*20percent~id~'e2~period~900))~(~'Uniswap~'ON_CHAIN_QUOTE_PROVIDER_EXACT_OUT_TRAFFIC_SAMPLING_CHAIN_ID_1~'Service~'RoutingAPI~(id~'m1~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_SAMPLING_CHAIN_ID_1~'.~'.~(id~'m2~visible~false))~(~'.~'ON_CHAIN_QUOTE_PROVIDER_EXACT_IN_TRAFFIC_TOTAL_CHAIN_ID_1~'.~'.~(id~'m3~visible~ …
> live switch mainnet quote for 100 percent

- lib/handlers/injector-sor.ts
- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- lib/util/onChainQuoteProviderConfigs.ts
This pull request introduces changes that enable shadow sample mixed quoter on Base.
The code now includes logic to use a different quoter ('0xe544efae946f0008ae9a8d64493efa7886b73776') when the useMixedRouteQuoter flag is enabled.
Test by setting the useMixedRouteQuoter to true and observe if the shadow sample mixed quoter is being used.
Because we want to try out the mixed quoter on Base, before we proceed to support mixed quoting on different L2s.
---
> shadow sample mixed quoter on Base at 1%

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- test/mocha/integ/handlers/quote/provider-migration/traffic-switch-quote-provider.test.ts
This reverts commit 3a8199d2b4ab9d8930e16be2faced71279397b5d.
Since last friday, we realized the slight drop in success rate in Polygon and Mainnet had nothing to do with the view-only quoter enablement, but the division by zero error.
> Revert "Revert live switch of Mainnet and Polygon (#646)"

- bin/stacks/routing-caching-stack.ts
- lib/handlers/injector-sor.ts
- lib/handlers/router-entities/aws-subgraph-provider.ts
- lib/util/poolCachingFilePrefixes.ts
In this part, we will download the compressed s3 pool files and decompress them in-memory, with the fallback to the plain-text s3 pool files.
I cross checked the pool sizes between the plain text and compressed
- mainnet V2 subgraph
- mainnet V3 subgraph
- base V3 subgraph
and they all look aligned.
In addition, because we are adding this additional fallback logic per chain, in case some chains don't have the subgraph pool s3 files, they will take longer to fallback to static subgraph provider. We will preemptively check whether the cache-config contains the subgraph for such chain and such protocol version. If not, we fail fast to the static subgraph provider.
> feat: download compressed s3 pools with fallback

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
At 1% shadow sampling mixed quoter on Base, there's no traffic at all:
I want to increase to 100%, to see how many prod traffic will go through mixed routes, if at all.
> shadow sample mixed quoter on base at 100%

- bin/app.ts
Now that we've addressed the cold start via compressing the pool s3 files, we should be able to let beta integ-test consistently pass by hosting beta lambda at provisioned concurrency of 1.
> tune provisioned concurrency back down to 1 for beta

- lib/handlers/injector-sor.ts
- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We see some shadow mixed quotes on Base since I started in April 26th https://github.com/Uniswap/routing-api/pull/645:
Now we want to enable the mixed quotes on Base, so as to see how many more mixed quotes are now returned:
This indicates how much mixed quoter on Base improved the quotes.
> feat: enable mixed quote on base at 100%

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
I realized we have to sample celo and avax at some percent. The reason is because celo and avax doesn't have the non-shadow gas metrics for comparison:
This contrasts with other network, which has both non-shadow and shadow gas metrics for comparison, and for easy gas param tuning, for example on Base:
> chore: sample celo avax 1 percent

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
- lib/util/onChainQuoteProviderConfigs.ts
We are ready to tune the gas batch params in Celo to see if it can speed up. If we check the gas used on P97, P98, P99 and max levels:
we see the gas used drops significantly at P98 level to around ~3M per call. Since current batch param sets gas limit per call at 5M, we can drop it to around ~3M. Then we can increase the multichunk size to make sure each multicall can shoehorn more quote calls, reducing the number of RPC calls to multicall. We need to ensure that gas limit per call * multichunk size remains constant, or smaller, but not larger. So we choose 31200000 * 16 = 499200000, or 4.9M.
We choose Celo first, since it's lowest risk, meanwhile the traffic volume should be good enough to see quote endpoint latency improvements, if any.
> feat: tune Celo batch param for gas limit and multichunk size

- lib/handlers/quote/util/quote-provider-traffic-switch-configuration.ts
We no longer need to sample avax revert quoter, because we collected enough datapoints on how much gas used per call
> chore: stop sampling on avax

- lib/util/onChainQuoteProviderConfigs.ts
I think there's no need to retry failed on-chain quoter for Celo. If we look at max:
this tells me in the worst case scenario, we always exhausted all the attempts (2), and also the first time batch param vs the low success rate param do not improve success rate at all (0% -> 0%).
Then looking at p95 and p98:
It tells me, sometimes there's retry due to low success rate, otherwise it doesn't retry and just give up. In both cases, the success rate is low at 0%.
Eventually look at min:
This tells me that the min quote success rate still stays at 0%, despite no retry loop.
All those metrics together tells me, whether we retry or not, for those failed on-chain quoting, they will fail regardless of retry attempts. Therefore, there's no point in retrying, and hopefully with no retry, this brings …
> fix: no on-chain quote retry for celo

- lib/util/onChainQuoteProviderConfigs.ts
In previous PR https://github.com/Uniswap/routing-api/pull/667, I made the mistake of not lowering the success rate threshold to 0 for celo. This resulted in some quote returning http 500. The reason is because with no retry, but non-zero success rate threshold, SOR will throw [SuccessRateError](https://github.com/Uniswap/smart-order-router/blob/main/src/providers/on-chain-quote-provider.ts#L1072) now. I can repro via https://app.warp.dev/block/pkX8kMjwbWjrnPqcDrWG1d.
To fix, I will also lower the success rate threshold to 0, so that the error should no longer be repro-able https://app.warp.dev/block/XKXnXk9Fy2MpG7fpA4efov.
Since our beta pipeline only tests the basic quote on CELO, it won't touch the case where the first time on-chain quoting fails, so I explicitly disabled prod …
> lower success rate threshold to 0 for celo

- lib/handlers/injector-sor.ts
- package-lock.json
- package.json
i was looking at routing dashboard. I can see caching intent quote latency is improving on Blast after gas param tuning, but not quote intent quote latency:
This tells me we need to tune the gas param for quote-intent onchain quoting more aggressively. Right now we don't distinguish the metrics between quote-intent vs caching-intent metrics in onchain quoting. We will do so by bumping SOR https://github.com/Uniswap/smart-order-router/pull/568
> Log optimistic cached routes on-chain quoting metrics

- lib/handlers/injector-sor.ts
- lib/util/onChainQuoteProviderConfigs.ts
- package-lock.json
- package.json
Release SOR https://github.com/Uniswap/smart-order-router/pull/572.
On top of that, we will optimize the gas params for celo and avax even more. 
Celo P50 is:
Celo P75 is:
So Im going to lower gas limit to 80k for celo on optimistic cached routes path, which quote-intent quote endpoint.
Avax P50 is:
Avax P75 is:
I will lower gas limit to 60k for avax on optimistic cached routes path, which quote-intent quote endpoint.
> feat: tune gas param by optimistic cached routes and bump sor to v3.29.0

- lib/util/onChainQuoteProviderConfigs.ts
We are ready to tune the gas batch params in Op to see if it can speed up. If we check the gas used on P50:
optimistic P50 gas limit is around ~80k per call, meanwhile non-optimistic P50 is around 150k per call.  Right now we have 1.2M gas limit per call, which is too high. We decrease the gas limit respectively, so that we can increase the multichunk size for less multicall RPC calls over the network.
And if we look at the retry loop at P90:
less than 10% of the calls are retried even once, so we should go for some aggressive but still reasonable gas tuning on OP.
> feat: tune OP batch param for gas limit and multichunk size

- lib/util/onChainQuoteProviderConfigs.ts
We are ready to tune the gas batch params in BNB to see if it can speed up. If we check the gas used on P50:
gas limit on optimistic cached routes averages ~50k per call, meanwhile non-optimistic ones ~80k per call, so changing the gas limit and multichunk size that way.
Also checked BNB retried loops at P90 level:
On average it's still 0 retries, so it means we can try somewhat aggressive gas tuning on BNB.
> feat: tune bnb batch param for gas limit and multichunk size

- lib/util/onChainQuoteProviderConfigs.ts
We are ready to tune the gas batch params in Polygon to see if it can speed up. If we check the gas used on P50:
average gas limit per call is ~80k on optimistic cached routes. 
If we look at P75:
average gas limit per call is ~150k on optimistic cached routes. 
Look at P90 retried loops and retried calls, there are zero:
At P95, there starts to be some retries:
So this level of gas tuning should only affect less than 5% of the calls in increasing latencies, if any
> feat: tune polygon batch param for gas limit and multichunk size

- lib/util/onChainQuoteProviderConfigs.ts
We are ready to tune the gas batch params in Arbitrum to see if it can speed up. If we check the gas used on P50:
average gas limit per call is ~50k. 
If we check P75:
average gas limit per call is ~200k. 
If we check the retried loops and retried calls at P90, there's no retry:
At P95, there's slight retry, but not much:
> feat: tune arbitrum batch param for gas limit and multichunk size

- lib/util/onChainQuoteProviderConfigs.ts
Arbitrum gas tuning on optimistic cached routes was too aggressive. 
For retries, optimistic cached routes increased:
For latencies, optimistic cached routes also increased:
However, since non-optimistic cached routes latencies and retries stay the same, we can check their gas limit per call, and tune accordingly:
From non-optimistic cached routes, it appears 100k gas limits per call might be good.
> tune arbitrum on optimistic cached routes

- lib/util/onChainQuoteProviderConfigs.ts
After tuning gas limit to 100k, I see the latencies went back down to normal:
But I can see P50 gas limit is around 72k, so I'm trying to tune the gas limit lower to 75k:
> tune arbitrum gas lower to 75k

- lib/handlers/injector-sor.ts
There's certainly some [mixed routes on Base](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-1814400~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*27possible*20routes*20for*20type*20MIXED*27*20and*20chainId*20*3d*3d*208453*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*201000~queryId~'625782e588840af-8d8aec8f-4c64925-cbe0c0f1-b52b45f164a8ae344cde511c~source~(~'*2faws*2flambda*2fprod-us-east-2-RoutingAPI-Ro-RoutingLambdaF7AD8A1A-erFTueZgLnZ1~'*2faws*2flambda*2fprod-us-east-2-RoutingAPI-R-RoutingLambda2C4DF0900-Bbcx5MI4vlM6))) Since I shadow sampled on April 26th. But, since I enabled live mixed quotes …
> disable new mixed quoter on Base

- lib/util/onChainQuoteProviderConfigs.ts
We are ready to tune the gas batch params in Base to see if it can speed up. If we check the gas used on P50:
gas limit on optimistic cached routes averages ~75k per call.
If we check P75:
Non-optimistic gas limit is ~200k.
> feat: tune base gas on optimistic cached routes

- lib/util/onChainQuoteProviderConfigs.ts
Base on the optimistic cached routes is lowered to 75k gas limit per call, and we see increase in retries:
Since non-optimistic path of 200k gas limit doesn't cause increase in retries, so somewhere between 75k-200k is good.
At P75 gas, I see the non-optimistic gas limit is ~100k:
So Im thinking to increase optimistic gas limit from 75k to 100k as a heuristic.
Overall, by lowering to 75k gas limit doesnt change the onchain quoting latency, so it means even though we have more retries, the increased batch size offset the retries in the overall latencies:
which means we should either expect to see improved latency from this PR, or still no latency improvement on Base.
> fix: increase base gas limit to 100k

- lib/handlers/injector-sor.ts
- lib/util/onChainQuoteProviderConfigs.ts
- package-lock.json
- package.json
Release SOR on https://github.com/Uniswap/smart-order-router/pull/576
On top of that, we only ensure to tune Mainnet gas param for V3, not mixed quoter, because mixed quoter is still gas-inefficient.
Then we are ready to look at P50 gas:
Also P75:
At P50, optimistic cached routes gas limit averages around 50k, meanhile P75, non-optimistic is about ~150k. We will tune V3 part of the mainnet quote to see if the V3 onchain quote latencies can improve. It's hard to see endpoint latency improvement for mainnet due to mixed onchain quoting.
> feat: tune mainnet batch param for gas limit and multichunk size

- bin/stacks/routing-lambda-stack.ts
- lib/config/rpcProviderProdConfig.json
- lib/rpc/utils.ts
Alchemy provisioned fast endpoint on some chains, but Sepolia is not one of them. We will use Infura as primary provider on Sepolia and Alchemy only as fallback.
On some chains, the API keys will be updated, so we bump lambda version to pick those up from the secrets.
> fix: remove alchemy from the fast endpoint on Sepolia

- lib/rpc/utils.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
Alchemy fast endpoint has the format of https://{CHAIN_NAME}-{testnet|mainnet}-fast.g.alchemy.com/v2/{API_KEY}
Fix in our code to reflect that.
> fix: alchemy fast endpoint update

- lib/rpc/SingleJsonRpcProvider.ts
In order to get the most accurate latency measure for each RPC method, we will shuffle the latency measurement to be exactly where the RPC method invocation happens.
In addition, we will log high latency alchemy RPC method request payload, so as to collaborate to debug.
> fix: measure rpc methods latencies right around the call

- lib/config/rpcProviderProdConfig.json
- lib/rpc/utils.ts
- test/mocha/unit/rpc/GlobalRpcProviders.test.ts
Alchemy provisioned sepolia fast endpoint. We can switch now on Sepolia.
> fix: use alchemy fast endpoint on sepolia

- lib/handlers/injector-sor.ts
- lib/handlers/quote/quote.ts
- lib/rpc/UniJsonRpcProvider.ts
I find we are also shadow evaluating providers' latencies during [quoteInjector](https://github.com/Uniswap/routing-api/blob/e5827cfd59df80bb234e47727db2495d80da6471/lib/handlers/index.ts#L13). This can only happen during the lambda initialization time. We should not evaluate during the lambda initialization time, but rather during the request processing path, a.k.a., within the quote handler.
> fix: only shadow evaluate providers latencies during request processing path

- lib/rpc/SingleJsonRpcProvider.ts
- lib/rpc/UniJsonRpcProvider.ts
Right now the logged evaluated latency [metric](https://github.com/Uniswap/routing-api/blob/e5827cfd59df80bb234e47727db2495d80da6471/lib/rpc/SingleJsonRpcProvider.ts#L205) doesn't distinguish different [CallType](https://github.com/Uniswap/routing-api/blob/e5827cfd59df80bb234e47727db2495d80da6471/lib/rpc/SingleJsonRpcProvider.ts#L24).
For the accurate providers' benchmarking, we definitely need to benchmark the same RPC method on the same type of evaluation metrics.
> fix: distinguish evaluate latency metrics from normall call metrics

- lib/config/rpcProviderProdConfig.json
In RPC_GATEWAY_1_[provider]_evaluated_2_latency_call metrics, I see that the latency ranking (from best to worst) is the same ordering as [providerUrls](https://github.com/Uniswap/routing-api/blob/main/lib/config/rpcProviderProdConfig.json#L55C6-L55C18). I have a hunch, because we fire and forget the [latencyEvaluation](https://github.com/Uniswap/routing-api/blob/1479b65f0865888094d50a98df30bbc149226cd3/lib/rpc/UniJsonRpcProvider.ts#L237), we might have messed up the latency measurement.
I want to test my theory by shuffling the shadow provider in mainnet in different sequence.
> fix: try shuffle the ordering of shadow providers in mainnet to see latencies evaluation change

- lib/rpc/UniJsonRpcProvider.ts
We should fire and forget shadow latency evaluation at the top level. However, for each provider latency evaluation, we should not fire and forget. This is because NodeJS runs on single thread, and we want to accurately benchmark each provider latency in a sequentially executed RPC method fashion.
> fix: fire and forget top level shadow latency evaluation

- lib/cron/cache-config.ts
Decreasing the threshold of the v2 untracked USD for the subgraph pools, this is just for metrics collection purposes.
> chore(cron): Reduce v2 threshold to 5k

- lib/config/rpcProviderProdConfig.json
- lib/rpc/UniJsonRpcProvider.ts
- test/mocha/unit/rpc/UniJsonRpcProvider.test.ts
On mainnet, so far we use the multi-provider probabilistic sampling upon instantiation. We want to change to always instantiate multi-providers. We want to keep other chains as is, because we care about mainnet latency for the most part.
Also we are removing the 10-minute time-based sampling window to allow more deterministic sampling at some probability per quote request. As a result, we add latencyEvaluationSampleProb and healthCheckSampleProb as extra safety measure. The probability was chosen from the previous shadow sampling rate when implementing view-only quoter:
1. mainnet 0.1% https://github.com/Uniswap/routing-api/pull/584
2. arbitrum 0.2% https://github.com/Uniswap/routing-api/pull/599
3. base 0.05% https://github.com/Uniswap/routing-api/pull/598
4. polygon 0.5% …
> fix: deterministic and probabilistic shadow evaluate latency across providers on mainnet

- lib/config/rpcProviderProdConfig.json
We see on mainnet, using multi-providers only have slight increase in latency evaluation calls, ~100 -> ~200 calls/min. We can expand to other chains to always use multi providers.
> fix: always use multi-providers across all chains

- package-lock.json
- package.json
Includes a change that allows V2 pools with untracked USD balances to be considered for routing
> Update SOR to 3.31.0

- lib/config/rpcProviderProdConfig.json
It's not obvious to me about the quicknode reth perf, because the quicknode latency is now a mix of reth and geth. I'm removing geth shadow calls.
> feat: remove quicknode geth to see pure reth perf

- lib/config/rpcProviderProdConfig.json
Infura now having issue across op, arb, and avax. Our quote endpoint success rate below 10%. We have to urgently switch over to quicknode
> fix: manually fail over op, arb, avax traffic to quicknode geth

- lib/rpc/SingleJsonRpcProvider.ts
- lib/rpc/UniJsonRpcProvider.ts
Our new provider is asking whether we can have a break of methods via send RPC invocations. We are logging such metric. Also clean up the log.error to include the error object, so that the error callstack can also be logged for easier debugging.
> chore: add send method metrics

- lib/cron/cache-config.ts
we see HarryPotterObamaSonic10Inu (BITCOIN) going through  [V2] 100.00% = WETH -- [0x1058E2644E066031B7b4a76a4bB42208838eF938] --> FATMOM -- [0xA7776F25cc032549b7517154c0F0164db94478BA] --> BITCOIN. We think it might be related to filtering subgraph pools by untracked usd threshold in recent changes. We set that to max on v2 mainnet, so we only filter by tracked eth threshold.
> fix: set untracked usd threshold to max on v2 mainnet

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
We still include FATMOM in the ETH -> HarryPotterObamaSonic10Inu (BITCOIN) quote route, despite the subgraph pool filtering logic changed to not consider untracked usd pools. I think this is because in caching intent routing-api lambda invocation, we keep hitting the ETH -> FATMOM -> HarryPotterObamaSonic10Inu (BITCOIN) routes from dynamo, but also getting the fresh routes from subgraph pools. However in SOR, it just meshes all those routes together to do the best quote comparison. SOR doesn't invalidate the cached routes, if the fresh routes from subgraph pools no longer contains any of the cached routes.
> fix: manually filter out fantom cached routes

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
This reverts commit 3f68d2e62083268e683c4657c63869b8f8378f16.
This is an arbitrary fix, that is short-term. Also I figured out a way to delete the cached routes entry in dynamo DB, so in future, we shouldn't need to apply this kind of hack, if we need to make sure certain cached routes don't get returned.
> Revert "fix: manually filter out fantom cached routes (#712)"

- lib/config/rpcProviderProdConfig.json
We decided to 10x our shadow sampling RPC traffic to alchemy. Right now the RPC to Alchemy on mainnet, base, celo, polygon and op are about 50 RPS. 
We will increase to 500 RPS.
> chore: increase alchemy shadow sampling by 10x

- lib/config/rpcProviderProdConfig.json
We will keep increasing the sampling traffic to alchemy. in the meanwhile, we will remove nirvana, so that nirvana don't see the increase in sampling traffic at the same time.
> chore: remove nirvana from sampling and 5x alchemy sampling traffic

- lib/cron/cache-config.ts
The decentralized network from the graph is prone to timeouts or other errors, this setting will increase the retries to 5 to try to get more successful runs
> chore(subgraph-cache): Increase retries on decentralized network endpoints

- lib/config/rpcProviderProdConfig.json
- lib/rpc/utils.ts
We cannot name our secret as `QUICKNODE_TEST_1`. The reason is because in https://github.com/Uniswap/routing-api/blob/main/lib/rpc/ProdConfig.ts#L47, we extract provider name by the token before the first underscore. Then in https://github.com/Uniswap/routing-api/blob/main/bin/stacks/rpc-gateway-dashboard.ts#L15, we populate provider name for each chain. Having both `QUICKNODE_1` and `QUICKNODE_TEST_1` will result in duplicate provider name in the RPC dashboard, hence cdk bootstrap failure:
```
Error: There is already a Construct with name 'RoutingAPI-RpcGateway-ErrorRateAlarm-ChainId-1-Provider-QUIKNODE' in RpcGatewayFallbackStack [RpcGatewayFallbackStack]
at Node.addChild (/Users/siyu.jiang/workspace/routing-api/node_modules/constructs/src/construct.ts:403:13)
at new Node …
```
> fix: quicknode test key naming

- bin/stacks/routing-lambda-stack.ts
have to manually bump up the lambda version to pick up the new secret
> fix: bump lambda version to pick up secrets in env var

- bin/app.ts
Forgot to add `quicknodetest_1` into the secret fetch list, so that we hit runtime error:
```
2024-06-06T22:10:25.844Z	undefined	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Environmental variable QUICKNODETEST_1 isn't defined!","reason":{"errorType":"Error","errorMessage":"Environmental variable QUICKNODETEST_1 isn't defined!","stack":["Error: Environmental variable QUICKNODETEST_1 isn't defined!","    at Function.validateProdConfig (/lib/rpc/GlobalRpcProviders.ts:36:17)","    at Function.getGlobalUniRpcProviders (/lib/rpc/GlobalRpcProviders.ts:121:43)","    at <anonymous> (/lib/handlers/injector-sor.ts:168:35)","    at h (/node_modules/lodash/lodash.js:653:23)","    at Function.Kk (/node_modules/lodash/lodash.js:9622:14)"," …
```
> fix: add quicknodetest_1 into the secret fetch list

- README.md
- bin/app.ts
- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-lambda-stack.ts
- lib/handlers/injector-sor.ts
- package-lock.json
- package.json
We want to test out the new node endpoint latencies at 10% of prod traffic scale in shadow sampling.
tested on local routing-api:
> feat: shadow tenderly new node endpoint

- lib/handlers/injector-sor.ts
We want to double the tenderly node endpoint sampling traffic from 10% to 20%, to make sure the latencies stay consistent
> feat: double sampling tenderly node estimate gas api

- bin/stacks/routing-lambda-stack.ts
- lib/handlers/quote/injector.ts
I forgot to update the secret before merging the previous PR. Now the routing-api pipeline is stuck during the CDK update because it's not able to fetch the secret I newly created after the initial CDK update.
I'm manually bumping the lambda version to force re-picking new secrets.
> fix: bump lambda version to pick up new zksync secret

- bin/app.ts
From routing beta lambda:
```
"errorType": "Runtime.UnhandledPromiseRejection",
"errorMessage": "Error: Environmental variable ALCHEMY_324 isn't defined!",
"reason": {
"errorType": "Error",
"errorMessage": "Environmental variable ALCHEMY_324 isn't defined!",
"stack": [
"Error: Environmental variable ALCHEMY_324 isn't defined!",
"    at Function.validateProdConfig (/lib/rpc/GlobalRpcProviders.ts:36:17)",
"    at Function.getGlobalUniRpcProviders (/lib/rpc/GlobalRpcProviders.ts:121:43)",
"    at <anonymous> (/lib/handlers/injector-sor.ts:169:35)",
"    at h (/node_modules/lodash/lodash.js:653:23)",
"    at Function.gv (/node_modules/lodash/lodash.js:9622:14)",
"    at Lee.buildContainerInjected (/lib/handlers/injector-sor.ts:167:11)",
"    at Lee.build (/lib/handlers/handler.ts:51:41)",
" …
```
> fix: add missing ALCHEMY_324

- bin/stacks/routing-lambda-stack.ts
I forgot to add the secret `WEB3_RPC_324`, but it's actually being used in app.ts. I have to manually bump lambda version again.
> fix: bump lambda version again

- lib/cron/cache-config.ts
This PR migrates the V2 Subgraph Provider for the CachePools cron job from the decentralized network to Alchemy,
> chore(subgraph-cache): Migrate to Alchemy's subgraph

- package-lock.json
- package.json
Bump SOR version to 3.35.1 that contains the [fee fetcher cache fix](https://github.com/Uniswap/smart-order-router/pull/596)
Ran e2e tests against test aws environment
```
npm run test:e2e
211 passing (5m)
4 pending
```
> fix(caching): bump SOR version to 3.35.1

- README.md
- lib/cron/cache-config.ts
- lib/cron/cache-pools.ts
[wstETH/USDC](https://app.uniswap.org/explore/pools/ethereum/0x4622Df6fB2d9Bee0DCDaCF545aCDB6a2b2f4f863) and [wstETH/DOG](https://app.uniswap.org/explore/pools/ethereum/0x801c868ce08fb5b396e6911eac351beb259d386c) are liquid, so we will route through them.
I can see v3 [wstETH/USDC](https://app.uniswap.org/explore/pools/ethereum/0x4622Df6fB2d9Bee0DCDaCF545aCDB6a2b2f4f863) getting into the pools s3 file:
for [wstETH/DOG](https://app.uniswap.org/explore/pools/ethereum/0x801c868ce08fb5b396e6911eac351beb259d386c), I don't see it. But I think it's because alchemy v2-mainnet subgraph is only sync'ing around block 18701239, meanwhile the pool deployed at block [18737159](https://etherscan.io/block/18737159)
> fix: add wstETH/USDC and wstETH/DOG liquid pools for routing

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/605, which may unblock trading API team on the permit2 approval flow (TBD).
> chore: bump sor to 3.35.2

- test/mocha/e2e/quote.test.ts
routing-api release pipeline failed at beta integ-tests. This is because 0x2fEb1512183545f48f6b9C5b4EbfCaF49CfCa6F3 unwrapped WETH to ETH about an hour ago. So we find a new WETH whale, with EOA address for hardhat fork to impersonate the account against.
tests can pass on my local now https://app.warp.dev/block/N6mGlWwnAfgSf8g6MEXANi
> fix: new weth whale address to block fot test

- package-lock.json
- package.json
bump sor to 3.35.3 
- to pick up fee token fetch ttl cache increase to 20m
> chore: bump sor to 3.35.3

- lib/handlers/injector-sor.ts
- lib/util/onChainQuoteProviderConfigs.ts
decrease zksync gas limit from [3 million](https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/alpha-router.ts#L605) to 500k to increase the multicall batch size, hence improving latencies.
> lower zksync gas limit per quote from 3 million to 500k

- lib/handlers/shared.ts
The fix in https://github.com/Uniswap/routing-api/pull/745 should only apply to ZKSync, but it ended up impacting other networks as well, like mainnet.
> fix: routing config only on zksync

- .github/workflows/test.yml
- README.md
- bin/app.ts
- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-lambda-stack.ts
- lib/graphql/graphql-client.ts
- lib/graphql/graphql-provider.ts
- lib/graphql/graphql-queries.ts
- lib/graphql/graphql-schemas.ts
- lib/graphql/graphql-token-fee-fetcher.ts
- lib/handlers/injector-sor.ts
- test/mocha/integ/graphql/graphql-provider.test.ts
- test/mocha/integ/graphql/graphql-token-fee-fetcher.test.ts
- test/mocha/unit/graphql/graphql-provider.test.ts
Introducing a `GraphQLTokenFeeFetcher` (implementation + tests only for now, no live traffic)
This fetcher will use GraphQL endpoint to fetch token fee data, and will fallback to OnChain fetching if something goes wrong or to fetch any remaining tokens that couldn't be fetched from graphQL.
Did setup env variables `UNI_GRAPHQL_ENDPOINT` / `UNI_GRAPHQL_HEADER_ORIGIN` for GraphQL in routing-api
A separate PR will follow for shadow traffic,
- added unit/integration tests
- ran e2e tests with 100% GraphQL traffic
> feat: Introduce `GraphQLTokenFeeFetcher` (no traffic)

- lib/handlers/injector-sor.ts
- lib/util/traffic-switch/traffic-switcher-i-token-fee-fetcher.ts
- lib/util/traffic-switch/traffic-switcher.ts
- test/mocha/unit/traffic-switch/traffic-switcher-i-token-fee-fetcher.test.ts
- test/mocha/unit/traffic-switch/traffic-switcher.test.ts
Starting shadow sampling for `GraphQLTokenFeeFetcher` at `0.5%` of traffic.
This is only enabled on mainnet and, with recent caching changes, `0.5%` of traffic should be around `20 RPM` of sampling traffic (`avg 4k requests / min * 0.005 = 20 RPM`) (stats pulled from [here](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'TokenFeeFetcherFetchFeesSuccess~'Service~'RoutingAPI)~(~'.~'TokenFeeFetcherFetchFeesFailure~'.~'.)~(~'.~'TokenPropertiesProviderBatchGetCacheHit~'.~'.))~view~'timeSeries~stacked~false~region~'us-east-2~stat~'SampleCount~period~60)&query=~'*7bUniswap*2cService*7d*20TokenPropertiesProviderBatchGetCacheHit))
Also adding a generic `TrafficSwitcher<T>` to handle traffic switching/sampling on 2 implementations of …
> feat: Start GQL fee fetcher shadow sampling at 0.5% of traffic

- lib/util/traffic-switch/traffic-switcher-i-token-fee-fetcher.ts
Small logging update to surface comparison info in aws logs
> fix: update log to warn for token fetch sampling comparison

- lib/graphql/graphql-schemas.ts
- lib/graphql/graphql-token-fee-fetcher.ts
- test/mocha/integ/graphql/graphql-token-fee-fetcher.test.ts
From sampling traffic identified a small number of cases where graphql returns `feeData: null` and causing exception.
This was handled eventually with onChain fallback, but we want to handle correctly and keep sampling/comparing control and treatment.
> fix: graphql endpoint might return null feeData

- lib/util/traffic-switch/traffic-switcher-i-token-fee-fetcher.ts
- test/mocha/unit/traffic-switch/traffic-switcher-i-token-fee-fetcher.test.ts
Update on the sampling comparison logic between OnchainFeeFetcher and GraphQLFeeFetcher to ignore entries that are empty or have 0 fees and pollute comparison logs.
example
`TrafficSwitcherITokenFeeFetcher compareResultsForFetchFees: Different fee for address 0x4da27a545c0c5b758a6ba100e3a049001de870f5:  in control: {"buyFeeBps":{"type":"BigNumber","hex":"0x00"},"sellFeeBps":{"type":"BigNumber","hex":"0x00"}} and treatment: {}`
> fix: update token fetcher sampling comparison logic to ignore empty/0 fees

- lib/util/traffic-switch/traffic-switcher-i-token-fee-fetcher.ts
- test/mocha/unit/traffic-switch/traffic-switcher-i-token-fee-fetcher.test.ts
One more minor fix when comparing partially populated fees between the 2 implementations.
Populate with 0 so that we can have correct comparison.
> fix: Fee sampling comparison metrics when both undefined or buy/sellFeeBps missing

- lib/handlers/quote/quote.ts
- lib/util/gasLimit.ts
- test/jest/unit/handlers/quote.test.ts
the gas used proprietary SOR algorithm is too low on zksync, but tenderly cannot simulate on zksync yet to support accurate gas estimate. mobile launch on zksync requires a gas used, that will not result in mass onchain swap failure. We determined that routing-api returns a hardcoded 6 million gas used on zksync would avoid large onchain swap failures on mobile.
- tested locally with uniswap-web source, gas estimate doesn't change: https://app.warp.dev/block/dSlawsa6TBSS4MYWWSoSqj
- tested locally with uniswap-ios source, gas estimate changed to 6000000: https://app.warp.dev/block/th0bZOQCC3wUpgD1aVYkhI
> fix: hardcode gas on zksync

- lib/handlers/injector-sor.ts
Start traffic switch 2% to graphql token fee fetch, then we'll monitor and gradually increase.
2% should send ~3 req/sec to graphql endpoint
When we switch 100%, gql should expect around [~60 to 80 req/sec](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'GraphQLTokenFeeFetcherOnChainCallbackRequest~'Service~'RoutingAPI~(visible~false))~(~'.~'GraphQLTokenFeeFetcherFetchFeesSuccess~'.~'.~(visible~false))~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__NO~'.~'.~(visible~false))~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__YES~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesSuccess~'.~'.~(period~60))~(~'.~'TokenFeeFetcherFetchFeesFailure~ …
> chore(GQL): traffic switch 2% to graphql token fee fetch

- lib/handlers/injector-sor.ts
2% traffic ([PR](https://github.com/Uniswap/routing-api/pull/762)) [looks good ](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'GraphQLTokenFeeFetcherOnChainCallbackRequest~'Service~'RoutingAPI)~(~'.~'GraphQLTokenFeeFetcherFetchFeesSuccess~'.~'.)~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__NO~'.~'.~(visible~false))~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__YES~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesSuccess~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesFailure~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'us-east-2~stat~'SampleCount~period~60~start~'-PT12H~end~'P0D)&query=~'*7bUniswap*2cService* …
> chore(GQL): traffic switch 8% to graphql token fee fetch

- lib/handlers/injector-sor.ts
8% traffic (https://github.com/Uniswap/routing-api/pull/763) [looks good ](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'GraphQLTokenFeeFetcherOnChainCallbackRequest~'Service~'RoutingAPI)~(~'.~'GraphQLTokenFeeFetcherFetchFeesSuccess~'.~'.)~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__NO~'.~'.~(visible~false))~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__YES~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesSuccess~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesFailure~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'us-east-2~stat~'SampleCount~period~60~start~'-PT24H~end~'P0D)&query=~'*7bUniswap*2cService*7d*20T …
> chore(GQL): traffic switch 30% to graphql token fee fetch

- lib/handlers/injector-sor.ts
30% traffic (https://github.com/Uniswap/routing-api/pull/764) [looks good ](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'GraphQLTokenFeeFetcherOnChainCallbackRequest~'Service~'RoutingAPI)~(~'.~'GraphQLTokenFeeFetcherFetchFeesSuccess~'.~'.)~(~'.~'GraphQLTokenFeeFetcherFetchFeesFailure~'.~'.)~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__NO~'.~'.~(visible~false))~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__YES~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesSuccess~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesFailure~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'us-east-2~stat~'SampleCount~period~60~start~ …
> chore(GQL): traffic switch 70% to graphql token fee fetch

- lib/handlers/quote/quote.ts
- lib/util/estimateGasUsed.ts
- lib/util/estimateGasUsedUSD.ts
- test/jest/unit/handlers/util/estimateGasUsed.test.ts
after chatting with @ianlapham , we confirmed that extension also needs to have the zksync and celo gas hardcoded
> fix: extension also hardcode gas on zksync and celo

- bin/stacks/routing-api-stack.ts
Create an alarm for when GraphQLTokenFeeFetcherFetchFeesFailure rate goes above 15%.
We do have on chain fallback in place of GQL failure, but we want to be alerted if the failure rate is high to take action.
For this reason we only alert on SEV3.
> chore(gql): add sev3 alert

- lib/handlers/injector-sor.ts
70% traffic [looks good ](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'GraphQLTokenFeeFetcherOnChainCallbackRequest~'Service~'RoutingAPI)~(~'.~'GraphQLTokenFeeFetcherFetchFeesSuccess~'.~'.)~(~'.~'GraphQLTokenFeeFetcherFetchFeesFailure~'.~'.)~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__NO~'.~'.~(visible~false))~(~'.~'TRAFFIC_SWITCHER__TokenFetcherExperiment__fetchFees__COMPARISON__IDENTICAL__RESULT__YES~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesSuccess~'.~'.~(visible~false))~(~'.~'TokenFeeFetcherFetchFeesFailure~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'us-east-2~stat~'SampleCount~period~60~start~'-PT24H~end~'P0D)&query=~'*7bUniswap*2cService*7d* …
> chore(GQL): traffic switch 100% to graphql token fee fetch + shadow sample at 0.5%

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/628
> chore: bump sor to 3.35.11

- lib/cron/cache-pools.ts
wstETH/DOG subgraph returns 0 reserve:
It gets filtered out https://github.com/Uniswap/smart-order-router/blob/main/src/providers/v2/subgraph-provider.ts#L251.
We now will include wstETH/DOG pool manually in routing
> fix: wstETH/DOG manually included in subgraph pool

- lib/handlers/quote/quote.ts
- test/jest/unit/handlers/quote.test.ts
- This PR aims to remove the check for mobile, version < 1.24 to exclude V2 routing
- More context can be found in this [Slack](https://uniswapteam.slack.com/archives/C02GYG8TU12/p1720726497647639) thread
> feat: remove mobile check

- lib/handlers/quote/quote.ts
1. This PR aims to make a correction in #779
> fix: `forceProtocols` and not `mobileSource`

- lib/handlers/evm/provider/ProviderName.ts
We want to differentiate the latency metrics between quicknode geth vs reth. We do so by differentiating the provider name, based on part of the url, which is a substring of the domain name:
> seperate quicknode geth vs. reth metrics via different provider naming

- lib/rpc/UniJsonRpcProvider.ts
the GETH vs RETH mismatch is only from ETH_CALL RPC call. I noticed that such call has the block number as null in the input args, e.g.:
```
"methodName":"call","args":[{"data":"0x1749e1e30000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000320000000000000000000000000000000000000000000000000000000000000046000000000000000000000000000000000000000000000000000000000000005a000000000000000000000000000000000000000000000000000000000000006e000000000000000000000000000000000000000000000000000000000000008200000000000000000000000000000000000000000000000000000000000000960000000000000000000000000000000000000 …
```
> chore: log the mismatch call stack to understand why block number didn't get passed

- lib/rpc/SingleJsonRpcProvider.ts
- lib/rpc/UniJsonRpcProvider.ts
- test/mocha/unit/rpc/UniJsonRpcProvider.test.ts
I observe that RETH RPC calls are slower than GETH calls in Uniswap routing backend. My observation is based on two different time periods:
1. Between may 20th and may 21th, I had a [PR](https://github.com/Uniswap/routing-api/pull/701/files) that only samples quicknode reth and another [PR](https://github.com/Uniswap/routing-api/pull/704) that fail over from infura to quicknode geth. This means, before May 20th, I had the shadow sampling of mix of geth and reth, meanwhile between may 20th and may 21th, I had the shadow sampling of only reth.
request volume dropped in half on may 20th, because I changed from shadow sampling both quicknode geth and reth to shadow sampling only quicknode reth:
If reth were to run faster than geth, then I expect P50 latency to go down, but instead it went up: …
> chore: add RPC requests logging for RETH calls slower than GETH

- package-lock.json
- package.json
Updates SOR to the version that contains error logs for the subgraph class that is used in the cache cron.
> chore(sor): Bump SOR version

- lib/rpc/SingleJsonRpcProvider.ts
- lib/rpc/UniJsonRpcProvider.ts
- test/mocha/unit/rpc/UniJsonRpcProvider.test.ts
This reverts commit e0fc934112d5b66ea28401fff524bc0683fe0b28.
> Revert "chore: add RPC requests logging for RETH calls slower than GETH (#785)"

- lib/graphql/graphql-queries.ts
- lib/graphql/graphql-schemas.ts
- lib/graphql/graphql-token-fee-fetcher.ts
- package-lock.json
- package.json
- test/mocha/e2e/quote.test.ts
- test/mocha/integ/graphql/graphql-token-fee-fetcher.test.ts
In routing-api, we primarily get FOT fee from graphql now. We need to update the graphql schema to include those new boolean flags.
I tested with [DFNDR](https://etherscan.io/address/0x3f57c35633cb29834bb7577ba8052eab90f52a02#code#L331), which has transfer delay. For this token, we make sure the portion related fields are not returned:
- without simulation - https://app.warp.dev/block/hIpmVZNmkfCXYOvCbmTTFZ
- with simulation - https://app.warp.dev/block/a2bpiaw4cPHfnzglscwGIU
> fix: partially exclude fot from fee

- lib/graphql/graphql-provider.ts
Adds support for using GQL to get FOT info for all chains.
> fix(gql): get FOT from GQL for all supported chains

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/647
> chore: bump sor to 3.37.1

- package-lock.json
- package.json
Includes cross protocol liquidity pools.
> bump(sor): Update SOR version 3.38.0

- lib/handlers/injector-sor.ts
- package-lock.json
- package.json
We see no mismatch between tenderly api and tenderly node gas estimate on mainnet. We want to migrate from api to node at 1% of the live traffic first.
> feat: migrate to tenderly node endpoint at 1% on mainnet

- lib/handlers/injector-sor.ts
We migrated to tenderly node endpoint at 1%. P50 latency wise, the improvement is very noticeable between tenderly api and tenderly node:
response volume wise, we see slight increase in node 200 response, and no other http status:
But the absolute tenderly node traffic volume is not high enough, so we don't see overall quote endpoint latency improvement. We are ramping up to 10% tenderly node volume to see if the quote endpoint latency has noticeable improvements.
> feat: migrate to tenderly node endpoint at 10% on mainnet

- lib/handlers/injector-sor.ts
We migrated to tenderly node endpoint at 10%. latency wise overall we have not seen a big difference
> feat: migrate to tenderly node endpoint at 50% on mainnet 

- lib/handlers/quote/quote.ts
> chore(logging): add logging for 500 errors

- lib/graphql/token-fee-utils.ts
- test/mocha/integ/graphql/graphql-token-fee-fetcher.test.ts
Based on [this ask](https://uniswapteam.slack.com/archives/C03ESADBQPK/p1722878234324569?thread_ts=1722275677.840339&cid=C03ESADBQPK)
> fix(GQL): add new token to dynamic FOT list

- test/mocha/e2e/quote.test.ts
Need to investigate why GQL has flaky data
> fix(pipeline): Unblock pipeline due to flaky GQL data

- test/mocha/e2e/quote.test.ts
One blast integ-test with 1 weth trading amount keeps failing. It's due to blast pool's low liquidity. We lowered the trading amount from 1 weth to 0.01 weth and now the blast integ-test can all pass https://app.warp.dev/block/eHpCe18E8ywz63W6Z1Bz3q.
> fix: blast integ-test due to insufficient liquidity

- bin/stacks/routing-api-stack.ts
Exclude very low volume chains from 4xx alarm (no route).
Those alarms are very noisy due to low traffic and no liquidity.
[example](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#alarmsV2:alarm/RoutingAPI-SEV3-4XXAlarm-ChainId:%20324)
> fix(alarm): exclude very low volume chains from 4xx alarm (no route)

- lib/handlers/injector-sor.ts
- lib/handlers/router-entities/aws-subgraph-provider.ts
- package-lock.json
- package.json
routing-api needs to download v4 subgraph pools from s3 cache during lambda instantiation time. Based on the metrics, I can see that happened:
> feat: download v4 subgraph pools from s3 cache

- lib/handlers/injector-sor.ts
- lib/handlers/router-entities/aws-subgraph-provider.ts
- lib/handlers/shared.ts
- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/667
> chore: bump sor to 3.42.0 - feat: implement v4 candidate pools from top tvl v4 subgraph

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/672
> chore: bump sor to 3.43.1 - add 'division by zero' error logging

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/675
> chore: bump sor to 3.43.2 - fix: ticks crossing gas estimate

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/678
> chore: bump sor to 3.43.3 - fix: for token pair only quote against v2 quoter

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/683
> chore: bump sor to 3.46.1 - fix(sor): catch div zero + log but don't throw

- lib/handlers/quote/SwapOptionsFactory.ts
- lib/handlers/quote/quote.ts
- lib/util/SupportedProtocolVersions.ts
- lib/util/supportedProtocolVersions.ts
- package-lock.json
- package.json
- test/jest/unit/handlers/SwapOptionsFactory.test.ts
- test/jest/unit/handlers/quote.test.ts
- test/mocha/e2e/quote.test.ts
- test/mocha/unit/util/supportedProtocolVersions.test.ts
routing-api also accepts the 'x-universal-router-version' request header passed through from URA.
One way to validate the change is working, is that the existing v4 pool routing quote e2e test will fail without passing 'universal-router-version' header, as it defaults to universal router 1.2 in case of absent header: https://app.warp.dev/block/gUssmXhFujGDxGqywxEfOH
Then another local test, that adds 'universal-router-version' header with 2.0 will succeed, as that's the universal router version that will support v4 commands and v4 route planner: https://app.warp.dev/block/a1NCxqXzfuFPRAxZSUJJfm
> feat: accept universal router version request param from URA header 'x-universal-router-version'

- test/mocha/e2e/quote.test.ts
Previous [PR](https://github.com/Uniswap/routing-api/pull/827) didn't skip the test.
> chore: skip sepolia e2e test by removing the token check

- test/mocha/e2e/quote.test.ts
I didn't notice the routing-api pipeline was still failing because of another test. Unblock pipeline is important: https://app.warp.dev/block/zNoEdbo54XGmq42qap02Ff
> also do not run sepolia gas adjusted e2e test

- lib/cron/cache-config.ts
- package-lock.json
- package.json
- test/mocha/e2e/quote.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/696
Also, we should update the subgraph API url accordingly, because SOR now points to a newer deployed pool manager address.
Now we can unblock the sepolia v4 quote e2e test, that pool manager address is updated.
> feat: update subgraph and pool manager address

- lib/handlers/marshalling/cached-routes-marshaller.ts
- lib/handlers/marshalling/currency-amount-marshaller.ts
- lib/handlers/marshalling/route-marshaller.ts
- lib/handlers/marshalling/token-marshaller.ts
- lib/handlers/marshalling/v3/pool-marshaller.ts
- lib/handlers/marshalling/v4/pool-marshaller.ts
- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- lib/handlers/router-entities/route-caching/model/pair-trade-type-chain-id.ts
- package-lock.json
- package.json
- test/jest/unit/handlers/router-entities/route-caching/model/pair-trade-type-chain-id.test.ts
- test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
cached routes need to support native currency routing. This is important for v4 routing.
> chore: bump sor to 3.53.0 - feat: cached routes to support native currencies

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/708
> chore: bump sor to 3.54.0 - feat: support native currency in getting candidate pools from v4 subgraph

- package-lock.json
- package.json
Bumps SOR to v3.55 (+ v3-sdk to v3.14)
Supports additional fee tiers
Related SOR PR: https://github.com/Uniswap/smart-order-router/pull/704
> chore: bump SOR to v3.55 - feat: upgrade v3-sdk version + support additional fee tiers

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/719
> chore: bump sor to 3.58.0 - chore: update v4 quoter address and ABI

- lib/cron/cache-config.ts
- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- lib/handlers/router-entities/route-caching/model/pair-trade-type-chain-id.ts
- package-lock.json
- package.json
- test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/721.
I ran all the e2e tests against local routing-api instance, and saw that the cached routes hit rate is still significantly higher than miss rate, which gives me the confidence the change is working as expected:
> chore: bump sor to 4.0.0 - feat(breaking): top-level alpha router native currencyIn, currencyIn, quoteCurrency support

- lib/handlers/quote/quote.ts
- lib/handlers/schema.ts
- test/mocha/e2e/quote.test.ts
expose price impact for classic route, so that URA can cross compare against UniswapX quote.
> feat: expose price impact in routing-api response

- lib/handlers/shared.ts
On blast, ETH -> Blast consistently cannot get quote. This is because this quote requires split routes in routing, therefore routing lambda timed out:
From the screenshot, I can see the best rout is a 3 split route for this quote. So that I can just have max split of 3, instead of 7. I verify this via a special `debugRoutingConfig` field against prod quote endpoint, therefore it would override maxSplit of 7 in this request runtime:
```
curl 'https://interface.gateway.uniswap.org/v2/quote' \
-H 'origin: https://app.uniswap.org' \
--data-raw '{
"tokenInChainId":81457,
"tokenIn":"ETH",
"tokenOutChainId":81457,
"tokenOut":"0xb1a5700fA2358173Fe465e6eA4Ff52E36e88E2ad",
"amount":"1000000000000000000",
"type":"EXACT_INPUT",
"configs":[
{
"protocols":[
"V2",
"V3",
"MIXED"
], …
```
> fix: blast eth -> blast blast quote timeout

- lib/handlers/quote/injector.ts
- package-lock.json
- package.json
- test/mocha/e2e/quote.test.ts
chore: bump sor to 4.3.1
chore: bump sor 4.3.1 - fix: v4 subgraph not properly including native currency in v4 candidate pools
added ETH -> erc20 e2e quote test:
exact in https://app.warp.dev/block/TI4zj5GnBdCprZ4bZPJW2T
exact out https://app.warp.dev/block/iV65PwxmKtisG8leGNcwTn
> chore: bump sor to 4.3.1

- lib/util/estimateGasUsed.ts
- lib/util/gasLimit.ts
worldchain astrochain not supported on tenderly. we have to hardcode a higher gas limit, so that wallet and trading-api doesn't hit gas issue when submitting swap.
> fix: hardcode worldchain and astrochain gas limit

- package-lock.json
- package.json
- test/mocha/e2e/quote.test.ts
chore: bump sor to 4.6.0 - feat: tenderly support astrochain sepolia
re-enabling astrochain sepolia quote e2e tests, they all passed on my local: https://app.warp.dev/block/sbMpHGGDo53AfcPH7Tuc6J
can see tenderly sim success via a personal endpoint invoke https://app.warp.dev/block/abQCxMK2pP3XGQPOHsgnVI
> chore: bump sor to 4.6.0 - feat: tenderly support astrochain sepolia

- lib/config/rpcProviderProdConfig.json
Continue `unirpc` onboarding for routing API for all chains
BNB 10% traffic has been running on unirpc at 10% for ~2 weeks without issues.
This PR onboard all other chains as follows:
- **high volume** chains at `1%` (`Mainnet`)
- **mid volume** chains at `5%` (`Base, Arbitrum`)
- **low volume** chains at `10%` (all the rest)
Plan to monitor for a few days, then increase further.
Tested on private AWS + E2E tests with unirpc traffic ([dashboard](https://app.datadoghq.com/dashboard/3tp-vmc-q3n/unirpc-service-dashboard?fromUser=true&refresh_mode=paused&tpl_var_serviceid%5B0%5D=routing_api&from_ts=1728365806109&to_ts=1728366314804&live=false))
> feat(unirpc): onboard all chains at 1/5/10%

- lib/handlers/injector-sor.ts
Someone created a v2 WETH/USDC [pool](https://worldchain-mainnet.explorer.alchemy.com/address/0x5A5189307EAe50B0ef16EFF3812B798091A4dd52), without adding any liquidities. Therefore routing-api/SOR starts erroring out from error is from the v2 gas model https://github.com/Uniswap/smart-order-router/blob/main/src/routers/alpha-router/gas-models/v2/v2-heuristic-gas-model.ts#L291.
There's the same type of risk for astrochain sepolia, which is someone creates a v2 WETH/USDC pool on astrochain sepolia without adding liquidity. The same safest thing is to remove worldchain and astrochain sepolia from v2 support. both chains have v3 WETH/USDC with some liquidities.
Since routing-api e2e test enables worldchain and astrochain sepolia for quote tests, if there's an issue, code pipeline will fail. …
> fix: reomve worldchain and astrochain sepolia from v2 supported list

- package-lock.json
- package.json
showhorn:
- worldchain and unichain sepolia LP unblock, due to incorrect UniswapV2Router02
- sepolia v4 re-deploy
> fix: bump sor to 4.6.2 - bump sdk-core for worldchain and unichain sepolia v2 router

- lib/handlers/injector-sor.ts
- lib/util/extraV4FeeTiersTickSpacingsHookAddresses.ts
- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/751
> chore: bump sor to 4.7.1 - fix: v4 subgraph provider add ETH base token, and custom fee tier and tick spacings

- lib/handlers/injector-sor.ts
- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
I found out why cached routes cache invalidation doesn't work. Because we forgot to filter cached routes based on the blocks to live https://github.com/Uniswap/routing-api/blob/main/lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts#L478. 
I was first debugging against prod trading-api public endpoint https://app.warp.dev/block/ghxWNHwhcCy4P0n7qpqexD, on why it keeps returning a v4 pool, that returns a pool that doesn't even exist on the re-deployed v4 sepolia PoolManager[0xE8E23e97Fa135823143d6b9Cba9c699040D51F70]. Then I realized, the pool id 0xb793c6019fbdb95575103e55874d923da9386f689076f64659f1fff6bd3ac31f belongs to the previously deployed v4 sepolia  PoolManager. Then I realized, this is prob another cached routes becoming stale case.
then I was able to …
> fix: sepolia cached routes filter blocks to live to unblock v4 swap bug bash on sepolia

- lib/config/rpcProviderProdConfig.json
_**Note**: 
Plan to check this in later this week or coming Monday, once we monitor `unirpc` traffic switch that went live on Tue Oct 15th._
Continue unirpc onboarding for routing API for all chains
We have onboarded all chains at 10/30/50% without issues so far ([dashboard](https://app.datadoghq.com/dashboard/3tp-vmc-q3n/unirpc-service-dashboard?fromUser=true&refresh_mode=sliding&tpl_var_serviceid%5B0%5D=routing_api&from_ts=1729006934865&to_ts=1729021334865&live=true)).
This PR updates unirpc traffic for all chains as follows:
- **high volume** chains from `10%` to `30%` (`Mainnet`)
- **mid volume** chains from `30%` to `100%` (`Base, Arbitrum, Binance`)
- **low volume** chains from `50%` to `100%` (all the rest)
Plan to monitor for a few days, then fully onboard everything.
> feat(unirpc): switch traffic for all chains at 100% (Mainnet 30%)

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/750
> chore: bump SOR to 4.7.2 - fix: add v4 related split routes metrics and routeToString

- lib/cron/cache-config.ts
for example, below v4 pool from sepolia v4 subgraph has good liquidity and correct ETH:USDC sqrtPriceX96:
```
{
"id": "0xedfb549279d9a3179b88cffa6f3dbe0be9713cfef2a592ed84aa1866b5d6fe1e",
"token0": {
"symbol": "ETH",
"id": "0x0000000000000000000000000000000000000000"
},
"token1": {
"symbol": "USDC",
"id": "0x1c7d4b196cb0c7b01d743fbc6116a902379c7238"
},
"feeTier": "1500",
"tick": "-199337",
"tickSpacing": "30",
"liquidity": "78419054283340",
"hooks": "0x0000000000000000000000000000000000000020",
"totalValueLockedUSD": "4461.186564266090216538997840216723",
"totalValueLockedETH": "1.93727461978776941464871099029113",
"totalValueLockedUSDUntracked": "0",
"sqrtPrice": "3720139933953207328491692"
},
```
meanwhile below one has incorrect sqrtPriceX96 and bad liquidity:
```
{
"id": …
```
> fix: raise v4 subgraph totalValueLockedETH filtering threshold from 0 to 0.01 eth

- lib/cron/cache-pools.ts
- lib/util/extraV4FeeTiersTickSpacingsHookAddresses.ts
- lib/util/hooksAddressesAllowlist.ts
i just realized a bug, that routing-api/SOR is actually including the non-zero hooks v4 pools, due to how 1) routing-api subgraph cron job 2) SOR get-candidate-pools work together.
for context, yesterday i realized i forgot to pass in some v4 related alpha router params, when i was fixing the cached routes cache invalidation bug https://github.com/Uniswap/routing-api/pull/869/files#r1805582600. then i realized it doesn;t make sense, that it doesn;t make sense that the prod public trading-api endpoint can route through the v4 pool with the hardcoded hook address 0x0000000000000000000000000000000000000020 https://app.warp.dev/block/WQn2uwJFv6SxNzB4kGjOiO, as i was adding this hardcoded hook address in https://github.com/Uniswap/routing-api/pull/872/files#diff-f259fdf1090ba4d745924307d17fcefd …
> fix: filter out non-zero hooks address during v4 subgraph cron job

- lib/rpc/SingleJsonRpcProvider.ts
Sets timeout of rpc calls to `9s`.
Default was `120s` and we were hitting some concurrency spillover issues on provider blips and on `p99.99` ([dashboard](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2?graph=~(metrics~(~(~'Uniswap~'RPC_GATEWAY_1_UNKNOWN_evaluated_0_latency_call~'Service~'RoutingAPI~(id~'m5~label~'RPC_GATEWAY_1_UNKNOWN_evaluated_0_latency_call))~(~'.~'RPC_GATEWAY_1_QUIKNODE_GETH_evaluated_0_latency_call~'.~'.~(id~'m7~label~'RPC_GATEWAY_1_QUIKNODE_evaluated_0_latency_call))~(~'.~'RPC_GATEWAY_8453_UNKNOWN_evaluated_0_latency_call~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_8453_QUIKNODE_evaluated_0_latency_call~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42161_QUIKNODE_evaluated_0_latency_call~'.~'.~(visible~false))~(~'.~'RPC_GATEWAY_42161_UNKNO …
> fix(rpc): set timeout to 8s (default was 120s)

- lib/config/rpcProviderProdConfig.json
Continue unirpc onboarding for routing API for all chains
This PR updates unirpc traffic for all chains (except Mainnet) **more conservatively** as follows:
- **high volume** chains remain at `10%`  (`Mainnet`)
- **mid volume** chains from `50%` to `70%` (`Arbitrum, Binance`)
- **Base** chain from `20%` to `30%`
- Rest are already at `100%`
Plan to monitor, then keep gradual conservative onboarding.
> feat(unirpc): gradual traffic increase for unirpc - step 3

- lib/config/rpcProviderProdConfig.json
Disables all latency evaluation/health/sampling traffic from all chains.
Not needed anymore and can save some rpc traffic
> chore: disable latency sampling traffic

- lib/config/rpcProviderProdConfig.json
Continue unirpc onboarding for routing API for all chains
This PR updates unirpc traffic for all chains (except Mainnet) **more conservatively** as follows:
- **Binance** chain from `70%` to `100%`
- **Mainnet**  remains at `10%` 
- **Base** remains at `30%`
- **Arbitrum** remains at `70%`
- Rest chains are already at `100%`
Plan to monitor, then keep gradual conservative onboarding.
> feat(unirpc): gradual traffic increase for unirpc - step 4

- bin/stacks/routing-api-stack.ts
Some 5xx alerts are very noisy because of very low traffic, or because most traffic is no liquidity errors so denominator is very small.
Adjusting with an if condition to alert only if real traffic (excluding 4xx errors) is above 50 requests over 5 mins.
> fix(alerts): adjust noisy very low volume traffic alerts

- lib/handlers/quote/util/simulation.ts
- package-lock.json
- package.json
- test/jest/unit/handlers/util/simulation.test.ts
- test/mocha/e2e/quote.test.ts
Release https://github.com/Uniswap/smart-order-router/pull/759
> chore: bump to 4.7.8 - fix: return a new tenderly simulation status in case of tenderly downtime

- bin/stacks/routing-lambda-stack.ts
- lib/handlers/injector-sor.ts
- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
we want to try creating a new caching routing lambda for async lambda invocation, that will not get exposed through the api gateway. this separates the live path  from the async path through two different routing lambdas.
On my local routing dashboard, I tuned all cached routes rollout percent to 100%. I can see the caching intent charts are still there:
I also added a test to assert against the spied metric that hits the new caching routing lambda
> feat: add new caching route lambda for async routing invocation

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
we want to be able to understand what each cached routes entry item is in plain text. tried on my local:
> fix: also persist the plain text cached routes

- lib/handlers/quote/quote.ts
- test/mocha/e2e/quote.test.ts
we have some division by zero runtime error, due to trading amount being zero. trading amount cannot be zero, so we fail fast, by returning 400.
https://app.warp.dev/block/WPJHJVDpVHxYNbp6VLultL
> fix: zero trading amount

- lib/config/rpcProviderProdConfig.json
Moving `Mainnet` from 30% -> 50% to unirpc. 
`Base` is at `30%`
All other chains are onboarded `100%`
> chore(unirpc): Mainnet from `30% -> 50%`

- lib/config/rpcProviderProdConfig.json
Moving `Mainnet` from 50% -> 75% to unirpc. 
`Base` is at `30%`
All other chains are onboarded `100%`
> chore(unirpc): Mainnet from `50% -> 75%`

- lib/config/rpcProviderProdConfig.json
This change didn't go through due to flake e2e tests in pipeline.
Want to investigate some unirpc timeouts in mainnet last night before further increasing here.
Reverts Uniswap/routing-api#905
> Revert "chore(unirpc): Mainnet from `50% -> 75%`"

- package-lock.json
- package.json
Latest GETH client upgrade removes `totalDifficulty` https://github.com/ethereum/go-ethereum/releases. Hardhat released a fix to handle that https://github.com/NomicFoundation/hardhat/releases.
> fix: upgrade hardhat

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
tested on my local https://app.warp.dev/block/UAcbvZrb1zp5qX4efOjKRP
> fix: use plaintext routes column

- bin/stacks/routing-api-stack.ts
- lib/handlers/quote/quote.ts
tenderly simulation system down is swap blocking. we need to get alerted as sev2, and escalate to tenderly team asap.
also we need to add per-chain tenderly system down sev2, so that we can quickly comm to tenderly team, which chain(s) affected.
tested on personal aws account:
> fix: tenderly sim system down as sev2

- lib/util/tenderlyNewEndpointRolloutPercent.ts
1 percent looks good. mostly successful:
2 instances of timeouts:
> feat: migrate 10% of base traffic to new tenderly sim endpoint

- lib/handlers/injector-sor.ts
we should re-enable worldchain v2 routing, now that swap v2 router02 is re-deployed correctly.
> feat: enable worldchain v2 routing

- bin/stacks/routing-lambda-stack.ts
- cdk.context.json
1. put routing-api behind a vpc
2. created a vpc endpoint to connect to unirpc vpc endpoint service in uniswap-backend account
3. created route53 to point routing-dev to the vpc endpoint to avoid updating the endpoint on the service side.
> VPC endpoint to unirpc

- lib/graphql/token-fee-utils.ts
Adding TREND token to FOT gql skip list
Request by CX
> chore(gql): add TREND to FOT gql skip list

- package-lock.json
- package.json
Bump SOR to 4.8.2
Ships https://github.com/Uniswap/smart-order-router/pull/769
> chore: bump sor to 4.8.2 - fix(subgraph): include VIRTUAL/GAME pool in V2 Base subgraph

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/771
> chore: bump sor to 4.8.3 - fix(subgraph): include top 20 VIRTUAL/* pools in V2 Base subgraph

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/773
> chore: bump sor to 4.8.4 - fix(subgraph): include all 20 VIRTUAL/* pools in V2 Base subgraph

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/776
> chore: bump sor to 4.8.5 - fix: Use syntheticGasCostInTermsOfQuoteToken only if within 30% of gasCostInTermsOfQuoteToken

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/779
> chore: bump sor to 4.8.6 - fix: pass latest to tenderly node

- lib/config/rpcProviderProdConfig.json
Sending more traffic for base to unirpc now that we
- improved backend VPC setup with more EIPs
- improved Base quote search space reducing #rpc calls
> chore(unirpc): increase Base from 30% -> 50%

- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
Adding logs for tracing when we might be using expired cached routes in order for us to better trace and debug those occasions. 
There is a fix we might do to filter those out, but adding logging first will help us debug better the source of the problem.
> fix(cachedRoutes): add logs for tracing

- lib/util/gasLimit.ts
forgot to hardcode the gas estimate for BNB and ZORA, when I move both to tenderly not supported chains in https://github.com/Uniswap/smart-order-router/pull/782
> fix: bnb and zora hardcoded gas estimate

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/783
> chore: bump sor to 4.9.1 - fix: arb tenderly node endpoint

- lib/util/defaultBlocksToLiveRoutesDB.ts
Increase cachedRoutes TTL from 1h -> 12h for WorldChain
> fix: increase cachedRoutes TTL from 1h->12h for WolrdChain

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/790
> chore: bump sor to 4.10.1 - fix: ID_TO_NETWORK_NAME add unichain and monad testnet

- lib/config/rpcProviderProdConfig.json
Attempting to increase traffic again for Base on unirpc (after eips increase on backend).
Going from 50% to 75%
> chore(unirpc): Base traffic 50% -> 75%

- lib/config/rpcProviderProdConfig.json
Attempting to increase traffic again for Base on unirpc (after eips increase on backend + move to dedicated cluster).
Going from 75% to 100% and will monitor
> chore(unirpc): Base traffic 75% -> 100%

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/798
> chore: bump sor to 4.14.1 - add bytes32 non-null terminator logging

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/799
> chore: bump sor to 4.14.2 - add bytes32 non-null terminator token address logging

- lib/util/gasLimit.ts
- package-lock.json
- package.json
- test/jest/unit/handlers/util/estimateGasUsed.test.ts
reelase https://github.com/Uniswap/smart-order-router/pull/800
> fix: bump sor to 4.14.3 - fix: tenderly doesn't support monad testnet

- bin/app.ts
>Error: Environmental variable ALCHEMY_1301 isn't defined!
at Function.validateProdConfig (/lib/rpc/GlobalRpcProviders.ts:36:17)
at Function.getGlobalUniRpcProviders (/lib/rpc/GlobalRpcProviders.ts:132:43)
at <anonymous> (/lib/handlers/injector-sor.ts:200:35)
at h (/node_modules/lodash/lodash.js:653:23)
at Function.mC (/node_modules/lodash/lodash.js:9622:14)
at oie.buildContainerInjected (/lib/handlers/injector-sor.ts:198:11)
at oie.build (/lib/handlers/handler.ts:51:41)
at Object.<anonymous> (/lib/handlers/index.ts:13:74)
at Module._compile (node:internal/modules/cjs/loader:1364:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> fix: Environmental variable ALCHEMY_1301 isn't defined

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/803
> fix: bump sor to 4.16.1 - fix: add stateview and v4 quoter addresses

- lib/handlers/injector-sor.ts
forgot to enable v4 for arb base polygon bnb op avax world.
Now I can see base quote on my local - https://app.warp.dev/block/kWwQmnuWlGeTCZWXFgK3iB
> fix: enable v4 for arb base polygon bnb op avax world

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/809
> fix(cache): bump sor-4.17.4 - cache skip when not all protocols provided

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/812
E2E pass on personal aws
> chore: bump sor-4.17.6 - fix: don't explore split routes with native&wrappedNative

- test/mocha/e2e/quote.test.ts
Fix flaky comparison test
```
1) quote
mainnet alpha exactOut 2xx
+ Execute Swap
eth -> erc20:
AssertionError: expected '10000.000000000000000047' to equal '10000'
```
> fix(test): fix flaky e2e tests

- lib/util/hooksAddressesAllowlist.ts
- test/jest/unit/handlers/util/v4HooksPoolsFiltering.test.ts
flaunch hooks manually audited internally. we can manually allowlist non-upgradable hooks for beforeSwaps and afterSwaps, if it gains traction
> feat: manually allowlist flaunch hooks

- lib/util/v4HooksPoolsFiltering.ts
works on my local now https://app.warp.dev/block/EmntR2nA32Osn7MgZWmuZA
> fix: artifically inflate eth/fleth tvl to be picked up by routing

- lib/handlers/injector-sor.ts
- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/822
> chore: bump sor 4.17.11 - enable unichain support for mixed routes

- lib/cron/cache-config.ts
We are missing pool cache configs for
- Worldchain V2/V3 (both subgraphs available)
- Zora V3 (v2 subgraph not available)
> fix(poolCache): add missing L2 subgraph configs

- test/mocha/e2e/quote.test.ts
Reducing amount for flaky test as v4 ETH/USDC pool with very low liquidity might be selected, and liquidity changes often
> fix(e2e): adjust flaky e2e test

- lib/util/enableMixedRouteEthWeth.ts
@plondon mentioned they released web this AM (https://uniswapteam.slack.com/archives/C08DSTY7J1X/p1739569427618859). @Ayoakala mentioned they bumped sdks in trading-api https://github.com/Uniswap/external-api/pull/773. We are actually good to enable mixed route eth <-> weth for web, especially next week we are gonna bash this (https://uniswapteam.slack.com/archives/C07AD3507SQ/p1739570984797999).
> fix: enable mixed route eth <-> weth fix for web

- bin/app.ts
- lib/handlers/quote/quote.ts
- test/mocha/e2e/quote.test.ts
we want to cover e2e test with the cached routes cache miss codepath. we do so by leveraging the `debugRoutingConfig` so that the test will trigger the cache miss path deterministically.
> chore: include cache misses e2e tests

- lib/handlers/injector-sor.ts
- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/831
alll L2 tests passed https://app.warp.dev/block/Q43sdmGDmSdE8SKuB3Eh1m, L1 tests failure cannot be due to this change, because it does not touch any L1 logic at all.
> chore: bump sor to 4.18.2 - fix: support mixed quote on rest of L2s

- lib/handlers/injector-sor.ts
- package-lock.json
- package.json
Revert 'chore: bump sor to 4.18.2 - fix: support mixed quote on rest of L2s'
This reverts commit f569197e3230989cef30b917ed8bb16d9b5fde42.
> Revert 'chore: bump sor to 4.18.2 - fix: support mixed quote on rest of L2s'

- bin/stacks/routing-dashboard-stack.ts
Reverts Uniswap/routing-api#1024
Deployment for dashboard failed, reverting for now and will investigate
> fix: Revert "fix(dashboard): attempt to fix testnets widgets with errors"

- bin/stacks/routing-dashboard-stack.ts
Reverts Uniswap/routing-api#1029
This fix didn't really work
> Revert "fix(dashboard): attempt to fix testnets widgets with errors"

- README.md
- bin/app.ts
- bin/stacks/routing-api-stack.ts
- bin/stacks/routing-caching-stack.ts
- lib/cron/cache-config.ts
Alchemy is migrating a set of its subgraphs to a new account to split the indexing load. We need to migrate the v3/v4 subgraphs in routing to query from the new subgraph. We are starting with blast as it is one of the lower-traffic chains. Follow-up PRs will be filed for the remaining chains. 
I added a new secret to the Pipelines account, and made sure to update the ACL so that the routing account will be able to see it. 
This PR also removes the decentralized API key as it didn't look to be used anymore. 
`Tested locally:`
V3 Logs:
```
-25T18:53:06.559Z","v":0}
{
"name": "RoutingLambda",
"hostname": "169.254.75.251",
"pid": 11,
"level": 30,
"msg": "Got 3125 V3 pools from the subgraph. 95 after filtering",
"time": "2025-02-25T18:53:06.970Z",
"v": 0
}
{
"name": "RoutingLambda", …
```
> migrate blast v3/v4 subgraphs to new account

- test/mocha/e2e/quote.test.ts
disable USDC -> mockA force mixed route test, because someone made eth/mockA pool (https://uniswapteam.slack.com/archives/C07AD3507SQ/p1740074379045309?thread_ts=1739990355.165739&cid=C07AD3507SQ), and made the price impact 100% for the mixed route.
we can make a new mockB token for forcing mixed route test, but it's a chicken and egg, because someone will try to extract value against the mock pool again.
> chore: disable mockA test

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/833
> fix: bump SOR to 4.19.1 - fix: don't use cachedRoutes if intent.caching (1% experiment)

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/836
> fix: bump sor 4.19.4 - fix: don't use cachedRoutes if intent.caching (50% experiment)

- bin/app.ts
I forgot to exclude soneium from fetching the secrets. as a result, beta deploy failed:
>2025-03-06 08:46:02 UTC-0800
beta-us-east-2-RoutingAPI-RoutingLambdaStackNestedStackRoutingLambdaStackNestedStackRe-1IEZ6NNQOT7C4 
UPDATE_ROLLBACK_IN_PROGRESS
-
The following resource(s) failed to update: [CachingRoutingLambdaFB792963].
2025-03-06 08:46:02 UTC-0800
CachingRoutingLambdaFB792963 
UPDATE_FAILED
Likely root cause
-
Could not find a value associated with JSONKey in SecretString
> fix: do not fetch soneium RPC url from secrets

- test/mocha/e2e/quote.test.ts
ETH -> erc20 tests consistently failed, due to the incorrect test setup. In case of v4 only protocol, every chain has good enough liquidity to go through native pools now.
tested locally
- https://app.warp.dev/block/wbhIf8RyFzb0q06IjbL4Df
then fixed avax test:
- https://app.warp.dev/block/fQyuzsHVPdcRgkUYQfXW9Q
- https://app.warp.dev/block/QJ4uu16ewiYfcnwAcwtUSc
> fix: test assertion for v4 native

- lib/util/v4HooksPoolsFiltering.ts
top bunni hookful pool according to https://dune.com/queries/4813673/7977867. swap volume >= $200k. cross-check with https://bunni.xyz/explore/pools?chain=mainnet to see that they have non-trivial TVLs.
Since bunni uses external liquidities, uniswap v4-subgraph only has 0 TVL across all bunni hookful pools.
> feat: manually include some top swap volume bunni hookful pools

- lib/handlers/quote/quote.ts
- lib/handlers/quote/schema/quote-schema.ts
- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- package-lock.json
- package.json
routing-api side change complimentary of https://github.com/Uniswap/smart-order-router/pull/843/files. Online Routing lambda needs to send the hashed routeId to the async routing lambda, in order for async routing lambda to track how often cached routes changes metric
Tested in routing-api, I can see:
query string param cachedRoutesRouteIds
cachedRoutesNotChanged metrics
> chore: bump sor to 4.20.4 - log cached routes change metrics

- bin/stacks/rpc-gateway-dashboard.ts
- lib/config/rpcProviderProdConfig.json
WorldChain is still on QN -> move to unirpc
Manually tested
Also had to remove some (unused?) metrics from `RpcGatewayDashboard` due to some widget limitation.
```
2:37:27 PM | UPDATE_FAILED        | AWS::CloudWatch::Dashboard    | RpcGatewayDashboard
Resource handler returned message: "The dashboard body is invalid, there are 1 validation errors:
[
{
"dataPath": "/widgets",
"message": "Invalid number of metrics per dashboard (2566), the total is limited to 2500"
}
```
> fix: move worlchain to unirpc

- lib/handlers/quote/injector.ts
- lib/handlers/quote/schema/quote-schema.ts
we dont have a way to enable per-quote request debugging logging mode. this makes recent routing investigations harder. we need to enable debuggability in prod on demand to speed up the investigations.
One concrete example of the investigation difficulty is in https://uniswapteam.slack.com/archives/C021SU4PMR7/p1742316090353569?thread_ts=1741884189.239149&cid=C021SU4PMR7
local routing-api shows lots of logs, indicating debug on-demand works:
> feat: debug param

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/844
> chore: bump sor to 4.20.5 - fix: use v2 mixed quoter ABI for most chains

- test/mocha/e2e/quote.test.ts
pipline failed:
>  1) quote
mainnet alpha exactIn 2xx
+ Execute Swap
erc20 -> erc20 (uraVersion:2.0)
should hit cached routes true:
AssertionError: expected +0 to be above +0
+ expected - actual
at Context.<anonymous> (test/mocha/e2e/quote.test.ts:411:53)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
2) quote
mainnet alpha exactIn 2xx
+ Execute Swap
erc20 -> erc20 (uraVersion:2.0)
should hit cached routes false:
AssertionError: expected +0 to be above +0
+ expected - actual
at Context.<anonymous> (test/mocha/e2e/quote.test.ts:411:53)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
3) quote
mainnet alpha exactOut 2xx
+ Execute Swap
erc20 -> erc20 (uraVersion:2.0)
should hit cached routes true:
AssertionError: expected +0 to be above +0
+ …
> fix: test assert price impact

- package-lock.json
- package.json
Release https://github.com/Uniswap/smart-order-router/pull/848
> chore: bump sor to 4.20.9 - fix: UR v1.2 should have mixed route w/ v4 pool filtered out

- bin/stacks/routing-api-stack.ts
Low-volume chains/request sources alerts are very sensitive to small hiccups.
This PR increases the evaluation period from 2 to 4 for low-volume chains/request sources
- each period is 5mins so we'll get notified if alert lasts for 20 mins instead of 10mins)
> fix(alerts): increase evaluationPeriods for low-volume chains alerts

- bin/app.ts
routing-api didn't update the github connection from personal access token to code-star connection, see https://uniswapteam.slack.com/archives/C015DE5T719/p1743700451038299?thread_ts=1743642201.084969&cid=C015DE5T719.
we are updating the code to connect via codestar. note it also requires AWS admin to update routing-api pipeline policy to allow codestar connection. See past [commit](https://github.com/Uniswap/uniswapx-parameterization-api/commit/8be2eefdd9d751ee96d26494edd9baf641d395e3) from other repo as an example.
> fix: migrate routing-api pipeline github access token

- bin/stacks/routing-api-stack.ts
Low-volume chains/request sources alerts are very sensitive to small hiccups.
This PR increases the evaluation period from 2 to 4 for low-volume chains/request sources
each period is 5mins so we'll get notified if alert lasts for 20 mins instead of 10mins)
> fix(alerts): increase evaluationPeriods for low-volume chains alerts v2

- lib/handlers/quote/quote.ts
- lib/handlers/router-entities/route-caching/dynamo-route-caching-provider.ts
- package-lock.json
- package.json
- test/mocha/e2e/quote.test.ts
- test/mocha/integ/handlers/router-entities/route-caching/dynamo-route-caching-provider.test.ts
part 2 is to filter out the cached routes which happens to be mixed route, and when requested protocol versions include MIXED. We need to ensure, when this happens, mixed route needs to have exact requested protocol versions match, e.g. V2,V3, then MIXED routes has to include V2,V3 in protocolsInvolved.
Pending e2e test
> feat: get cached routes to filter out mismatched mixed routes against requested protocol versions

- lib/handlers/quote/quote.ts
increased from 1% -> 10%, not seeing perf change at P50, P90, and P99 level:
Now trying to increase 10% -> 50%, and see if we see P50 improvement.
> increase mixed latency fix to 50%

- lib/cron/cache-config.ts
I don't see BNB V4 cronjob lambda:
Because I forgot to add it into the cache-cron
> fix: add bnb protocol v4 subgraph cronjob

- lib/handlers/quote/quote.ts
Base seeing pert improvement, after ramping up 10% -> 50%:
ramping up from 50% -> 100%
> increase mixed latency fix to 100%

- lib/handlers/quote/quote.ts
- lib/handlers/quote/schema/quote-schema.ts
- package-lock.json
- package.json
routing-api query string param to accept hooksOption with enum NO_HOOKS, HOOKS_ONLY, or HOOKS_INCLUSIVE. Spec in https://linear.app/uniswap/issue/ROUTE-424/routing-without-hooks
> feat: routing-api support route hook toggle

- package-lock.json
- package.json
release https://github.com/Uniswap/smart-order-router/pull/859
> chore: bump sor to 4.21.1 - fix: make sure subgraph candidate pools loading can be hook toggled

- lib/util/hooksAddressesAllowlist.ts
sadly https://v4-ponder-production.up.railway.app/ is down, so that I don't have a way to query v4 pools by hooks addresses.  https://hookrank.io/8453/0x704268ac7043aeef50f47b6a03ae68ccf808e044/liquidity-pools doesn't show the exact pool address either.
> Allowlist Two New Hooks: BtcACC and MEVTaxTestInProd

- lib/handlers/quote/schema/quote-schema.ts
tested this makes hook toggle finally works.
HOOKS_ONLY against local endpoint - https://app.warp.dev/block/a1UGK525Rn8XHYcDN6amNt
HOOKS_ONLY against prod endpoint - https://app.warp.dev/block/yNYUdObrf1sPZRhsVZe04H
correct behavior is we no longer anticipate a hookless route through USD₮0 -> USDC on unichain, because we specified HOOKS_ONLY. However this case is not possible w/ current UI toggle design, so low priority.
NO_HOOKS against local endpoint - https://app.warp.dev/block/vjKOmHGdooiiqbkrYr1ByZ
NO_HOOKS against prod endpoint -https://app.warp.dev/block/4isnjJR0xpVhpB8RtJ4fKg
correct behavior is we no longer expect a hookful route through ETH -> flETH -> BHDG on base, because we specified NO_HOOKS. This is a high priority user story to support.
HOOKS_INCLUSIVE against local …
> fix: add hooksOption into quote schema

- lib/handlers/injector-sor.ts
fix: make sure we don't quote against mixed route when it does not contain a v4 pool.
when quoterAddressOverride does not have address, when mixed quote w/o v4 pool case, then we never quote against mixed w/o v4 pool. (https://github.com/Uniswap/smart-order-router/blob/main/src/providers/on-chain-quote-provider.ts#L433)
> fix: make sure we don't quote against mixed route when it does not contain a v4 pool

- package-lock.json
- package.json
only bypass cache when HOOKS_INCLUSIVE.
> chore: bump sor to 4.21.2 - fix: bypass cache when HOOK_INCLUSIVE

- lib/graphql/graphql-provider.ts
- lib/graphql/graphql-queries.ts
- lib/graphql/graphql-schemas.ts
- lib/graphql/graphql-token-price-fetcher.ts
- lib/handlers/injector-sor.ts
- lib/handlers/quote/injector.ts
- lib/handlers/quote/quote.ts
- lib/handlers/quote/schema/quote-schema.ts
- lib/handlers/shared.ts
- package-lock.json
- package.json
- test/mocha/e2e/quote.test.ts
- test/mocha/integ/graphql/graphql-token-price-fetcher.test.ts
Ships https://github.com/Uniswap/smart-order-router/pull/860 (pending checkin)
**Note**: _had to update several e2e tests related to `hitsCachedRoutes`. Also had to introduce a hardhat fork snapshot/revert before/after each test to prevent tests failign due to pool liquidities changes after large swaps (large swaps now are more accurate, discovering more liquidity, altering more pools)_
Added e2e tests
> chore: bump sor to 4.21.2 - feat: skip cachedRoutes for large swaps

- lib/cron/cache-config.ts
try increasing the base tracked ETH TVL threshold to upload less V2 base subgraph pools to routing's s3 bucket.
> fix: increase v2 base subgraph ETH tracked threshold 0.025 -> 0.1 ETH

- package-lock.json
- package.json
Ship https://github.com/Uniswap/smart-order-router/pull/869
> chore: bump SOR to 4.21.8 - fix: base v3 subgraph filtering update

- package-lock.json
- package.json
ship https://github.com/Uniswap/smart-order-router/pull/870
> chore: bump SOR to 4.21.9 - fix: base v3 subgraph filtering update v2

- package-lock.json
- package.json
Ship https://github.com/Uniswap/smart-order-router/pull/871
> chore: bump SOR to 4.21.10 - fix: all v3 subgraph filtering update

- package-lock.json
- package.json
https://github.com/Uniswap/smart-order-router/pull/874
> chore: bump sor to 4.21.11 - fix: ROUTE-486 Route BtcAcc

- package-lock.json
- package.json
Bumping up version to 4.21.16
releasing: https://github.com/Uniswap/routing-api/pull/1116
> chore: Bumping up version to 4.21.16

- package-lock.json
- package.json
ship https://github.com/Uniswap/smart-order-router/pull/882
> fix: bump sor 4.21.17 - filter out direct v3 pool with rebase token breaking routing

- bin/stacks/routing-caching-stack.ts
IPFS caching job stuck because subgraph alchemy provider missing alchemy API KEY in the lambda env var, see https://uniswapteam.slack.com/archives/C08TV5WJL07/p1749654860726899
> fix: add alchemy subgraph key to IPFS caching lambda

- test/mocha/e2e/quote.test.ts
1 ETH trade size can make no route https://app.warp.dev/block/GLd5t3E75KK04hqm5Q6MsP
> fix: lower v4 trade size during e2e tests

- test/mocha/e2e/quote.test.ts
ignore low v4 liquidity e2e tests to unblock the pipeline
> fix: skip low v4 liquidity e2e tests siyujiang/skip-low-v4-liquidity-e2e-tests

- lib/cron/cache-pools.ts
we are seeing `TypeError: Cannot read properties of undefined (reading 'eulerHooksProvider')` on some subgraph. cron jobs, after https://github.com/Uniswap/routing-api/pull/1143. the reason is because not every subgraph pool cron job has the `eulerHooksFactoryProvider` instantiated, hence we need to have null check protection.
I tested on my personal aws account, and i no longer see erroring out:
> fix: euler hooks factory provider null check

- lib/handlers/injector-sor.ts
Seeing some issues with v3+v4 routes on optimism.
Removing support for now for further investigation
> fix: remove mixed route support from optimism

- lib/handlers/injector-sor.ts
Enabling cache invalidation during simulation failure for UniChain
> ROUTE-574 enable unichain

- lib/handlers/injector-sor.ts
ROUTE-574 Support more chains
Only left `MAINNET, ARBITRUM_ONE, POLYGON, BNB, and BASE` disabled.
> ROUTE-574 Support more chains

- lib/handlers/injector-sor.ts
we see optimism and base have mixed routes working now, especially with base v3 jacob/eth against v4 zora creator pools and content pools, with v3 against v4 mixed cross liquidity candidate pools. we are enabling mixed routes to the rest of L2s.
> enable mixed routes across L2s

- bin/stacks/routing-lambda-stack.ts
increase routing caching lambda timeout to cache more complex routes
> fix: increase routing caching lambda timeout 18s -> 30s
